---
title: "session 2 notes"
author: "Derek Sollberger"
format: html
---

# Mean

1.  add up the numbers
2.  divide by the amount of numbers

to run a line of code: CTRL + ENTER

"c" for concatenate ("combine")

```{r}
some_data <- c(32, 45, 16, 78, 39)
sum(some_data)
length(some_data)
sum(some_data) / length(some_data)
mean(some_data)
```

## Missing Data

NA for not applicable ("missing data")

R stops calculations upon missing data

    * want to avoid the missing data

```{r}
some_data2 <- c(32, 45, 16, 78, NA, 39) #another list
mean(some_data2)
mean(some_data2, na.rm = TRUE)
```

# Median

```{r}
some_data
sort(some_data)
median(some_data)

some_data3 <- c(32, 45, 16, 78, 39, 5)
sort(some_data3)
median(some_data3)
```

# Olympics

## Load Data

```{r}
olympic_df1 <- readr::read_csv("https://raw.githubusercontent.com/dsollberger/sml201slides/main/posts/02_centrality/olympic_data.csv")
olympic_df2 <- readr::read_csv("https://raw.githubusercontent.com/dsollberger/sml201slides/main/posts/02_centrality/olympic_data2.csv")
```

## Explore Data

```{r}
head(olympic_df1)
str(olympic_df1) #structure
colnames(olympic_df1) #column names
```

```{r}
mean(olympic_df1$weight)
mean(olympic_df1$weight, na.rm = TRUE)
summary(olympic_df1$weight)
```

```{r}
olympic_df1$weight[olympic_df1$weight <= 0] <- NA
olympic_df2$weight[olympic_df2$weight <= 0] <- NA
```

```{r}
mean(olympic_df1$weight, na.rm = TRUE)
summary(olympic_df1$weight)
```

## Filter

```{r}
library("tidyverse")
```

```{r}
Turkey_df1 <- olympic_df1 |>
  filter(country_code == "TUR")
```








