{
  "hash": "ccbb230766fa9c870d6bf461666203c0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"7: Linear Regression\"\nauthor: \"Derek Sollberger\"\ndate: \"2026-02-17\"\nformat:\n  html:\n    toc: true\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"gt\")        #great tables\nlibrary(\"HistData\")  #historical data sets\nlibrary(\"tidyverse\") #tools for data wrangling and visualization\n\nliquor_df <- data.frame(\n  year = 2014:2023,\n  LLV = c(129, 54, 103, 50, 15, 10, 18, 49, 57, 262)\n)\nMM_df <- data.frame(\n  S = c(0.08, 0.12, 0.54, 1.23, 1.82, 2.72, 4.94, 10.00),\n  v = c(0.15, 0.21, 0.7, 1.1, 1.3, 1.5, 1.7, 1.8)\n)\n```\n:::\n\n\n\n# SML 201\n\n## Start\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n* **Goal**: Make predictions\n\n* **Objective**: Perform linear regression and compute coefficients of determination\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"60%\"}\n![linear regression](xkcd_2533.png)\n\n* image source: [XKCD](https://www.explainxkcd.com/wiki/index.php/2533:_Slope_Hypothesis_Testing)\n:::\n\n::::\n\n\n# Campus Example\n\n:::: {.panel-tabset}\n\n## Description\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\nThe following data on judicial referrals for liquor law violations come from the Princeton University [Annual Security and Fire Safety Report](https://publicsafety.princeton.edu/information/monthlyannual-data)  (in and around the main campus)\t\n\n![Clery Act Report](Clery_Report.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ayaihqsaff\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ayaihqsaff table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ayaihqsaff thead, #ayaihqsaff tbody, #ayaihqsaff tfoot, #ayaihqsaff tr, #ayaihqsaff td, #ayaihqsaff th {\n  border-style: none;\n}\n\n#ayaihqsaff p {\n  margin: 0;\n  padding: 0;\n}\n\n#ayaihqsaff .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ayaihqsaff .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ayaihqsaff .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ayaihqsaff .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ayaihqsaff .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ayaihqsaff .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ayaihqsaff .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ayaihqsaff .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ayaihqsaff .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ayaihqsaff .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ayaihqsaff .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ayaihqsaff .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ayaihqsaff .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ayaihqsaff .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ayaihqsaff .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayaihqsaff .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ayaihqsaff .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ayaihqsaff .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ayaihqsaff .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayaihqsaff .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ayaihqsaff .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayaihqsaff .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ayaihqsaff .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayaihqsaff .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ayaihqsaff .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ayaihqsaff .gt_left {\n  text-align: left;\n}\n\n#ayaihqsaff .gt_center {\n  text-align: center;\n}\n\n#ayaihqsaff .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ayaihqsaff .gt_font_normal {\n  font-weight: normal;\n}\n\n#ayaihqsaff .gt_font_bold {\n  font-weight: bold;\n}\n\n#ayaihqsaff .gt_font_italic {\n  font-style: italic;\n}\n\n#ayaihqsaff .gt_super {\n  font-size: 65%;\n}\n\n#ayaihqsaff .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ayaihqsaff .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ayaihqsaff .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ayaihqsaff .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ayaihqsaff .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ayaihqsaff .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ayaihqsaff .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ayaihqsaff .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ayaihqsaff div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\" style>Liquor Law Violiations</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>(judicial referrals)</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"year\">year</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"LLV\">LLV</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #B0315B; color: #FFFFFF;\">2014</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #B0315B; color: #FFFFFF;\">129</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #370962; color: #FFFFFF;\">2015</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #370962; color: #FFFFFF;\">54</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #87216B; color: #FFFFFF;\">2016</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #87216B; color: #FFFFFF;\">103</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #300A5B; color: #FFFFFF;\">2017</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #300A5B; color: #FFFFFF;\">50</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #02020C; color: #FFFFFF;\">2018</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #02020C; color: #FFFFFF;\">15</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #000004; color: #FFFFFF;\">2019</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #000004; color: #FFFFFF;\">10</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #040312; color: #FFFFFF;\">2020</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #040312; color: #FFFFFF;\">18</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #2E0B5A; color: #FFFFFF;\">2021</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #2E0B5A; color: #FFFFFF;\">49</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #3C0965; color: #FFFFFF;\">2022</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #3C0965; color: #FFFFFF;\">57</td></tr>\n    <tr><td headers=\"year\" class=\"gt_row gt_center\" style=\"background-color: #FCFFA4; color: #000000;\">2023</td>\n<td headers=\"LLV\" class=\"gt_row gt_center\" style=\"background-color: #FCFFA4; color: #000000;\">262</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"> Princeton University, Main Campus</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n\n::::\n\n## gt code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  gt() |>\n  cols_align(align = \"center\") |>\n  tab_footnote(footnote = \"Princeton University, Main Campus\") |>\n  tab_header(\n    title = \"Liquor Law Violiations\",\n    subtitle = \"(judicial referrals)\"\n  ) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  data_color(\n    columns = LLV,\n    target_columns = everything(),\n    palette = \"inferno\",\n    reverse = FALSE\n  )\n```\n:::\n\n\n::::\n\n# Short Way\n\n## Linear Regression in R\n\n* response variable (y): `LLV`\n* explanatory variable (x): `year`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_fit <- lm(LLV ~ year, data = liquor_df)\n```\n:::\n\n\nIn a model equation, the tilde `~` is read as \"explained by\".  In this model, we can say that the response variable `LLV` is explained by the `year`.\n\n## Prediction in R\n\nWe use the `predict` function where the input is a data frame.  In this example, we are predicting the number of judicial referrals for liquor law violations in the year 2024.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyhat <- predict(lin_fit,\n                newdata = data.frame(year = 2024))\n```\n:::\n\n\n## Validation\n\nIn this simple example, we know the true answer: there were 218 judicial referrals for liquor law violations in the year 2024\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# true value\ny <- 218\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# prediction\nprint(yhat)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n102.9333\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# absolute error\nabs(y - yhat)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n115.0667\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# relative error\nabs(y - yhat) / y\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n0.5278287\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n# DCP1\n:::\n\n\n# Deep Dive\n\n## Scatterplot\n\nIt is a good idea to *look at the data* (when practical).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  ggplot() +\n  geom_point(aes(x = factor(year), y = LLV),\n             size = 4, color = \"black\") +\n  labs(title = \"Liquor Law Violations\",\n       subtitle = \"Princeton University, main campus\",\n       caption = \"SML 201\",\n       x = \"year\", y = \"judicial referrals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n## Smooth\n\nOn the visual size, linear regression summarizes a scatterplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  ggplot(aes(x = factor(year), y = LLV)) +\n  geom_point(size = 4, color = \"black\") +\n  geom_smooth(formula = \"y ~ x\", method = \"lm\", se = FALSE,\n              color = \"blue\", linewidth = 2) +\n  labs(title = \"Liquor Law Violations\",\n       subtitle = \"Princeton University, main campus\",\n       caption = \"SML 201\",\n       x = \"year\", y = \"judicial referrals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## Corollary: Centroid\n\n**Claim**: a linear regression model goes through the centroid \n\n$$(\\bar{x}, \\bar{y})$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(liquor_df$year)\nybar <- mean(liquor_df$LLV)\n\nliquor_df |>\n  ggplot(aes(x = year, y = LLV)) +\n  geom_point(size = 4, color = \"black\") +\n  geom_vline(xintercept = xbar, color = \"green\") +\n  geom_hline(yintercept = ybar, color = \"green\") +\n  geom_smooth(formula = \"y ~ x\", method = \"lm\", se = FALSE,\n              color = \"blue\", linewidth = 2) +\n  labs(title = \"Linear Regression\",\n       subtitle = \"A linear regression model goes through the centroid \",\n       caption = \"SML 201\",\n       x = \"year\", y = \"judicial referrals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Vector Space\n\nHow was the line drawn?\n\n![Where to draw the line?](many_splits.gif)\n\n# Deeper Dive\n\n::: {.callout-note}\n## Linear Model Form\n\n$$\\hat{y} = a + bx$$\n\n* $\\hat{y}$: predicted value\n* $a$: intercept\n* $b$: slope\n\n:::\n\n\n## Formulas\n\n::: {.callout-note}\n## Simple linear regression\n\n$$\\hat{y} = a + bx$$\n\n\nFor **simple linear regression** (today's materials, before more complicated models), the intercept and slope can be written in terms of previously studied sample statistics:\n\n$$b = r \\cdot \\frac{s_{y}}{s_{x}}, \\quad a = \\bar{y} - b*\\bar{x}$$\n\n:::\n\n::: {.callout-tip}\n## Concept Map\n\nWith slope $b$ defined as\n\n$$b = r \\cdot \\frac{s_{y}}{s_{x}}$$\n\nin simple linear regression, and recalling that\n\n$$s_{x} > 0 \\quad\\text{and}\\quad s_{y} > 0$$\n\nfor non-trivial examples (i.e. data is not constant), it follows that\n\n* slope of regression line is positive iff correlation is positive\n* slope of regression line is negative iff correlation is negative\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Corollary: Centroid\n\n**Claim**: a linear regression model goes through the centroid \n\n$$(\\bar{x}, \\bar{y})$$\n\n**Proof**: \n\nThis proof is easy if we're allowed to start with these formulas\n\n$$y = a + bx, \\quad a = \\bar{y} - b*\\bar{x}$$\n\nWe then verify that $(x,y) = (\\bar{x}, \\bar{y})$ is a valid location in this model.\n\n$$\\begin{array}{rcl}\n  y & = & a + bx \\\\\n  \\bar{y} & = & a + b\\bar{x} \\\\\n  \\bar{y} & = & \\bar{y} - b*\\bar{x} + b\\bar{x} \\\\\n  \\bar{y} & = & \\bar{y}\n\\end{array}$$\n\n:::\n\n# Residuals\n\nA *residual* is the difference between a predicted value and its true value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df <- liquor_df |>\n  mutate(predictions = predict(lin_fit,\n                               newdata = data.frame(year = liquor_df$year)),\n         residuals = predictions - LLV)\n```\n:::\n\n\n::::: {.panel-tabset}\n\n## plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  ggplot(aes(x = year, y = LLV)) +\n  geom_segment(aes(x = year, y = predictions, \n                   xend = year, yend = LLV), \n               color = \"purple\", linewidth = 3) +\n  geom_point(size = 4, color = \"black\") +\n  geom_smooth(formula = \"y ~ x\", method = \"lm\", se = FALSE,\n              color = \"blue\", linewidth = 2) +\n  geom_point(aes(x = year, y = predictions),\n             color = \"red\", size = 4) +\n  labs(title = \"Linear Regression\",\n       subtitle = \"black: true values\\nred: predictions\\npurple: residuals\",\n       caption = \"SML 201\",\n       x = \"year\", y = \"judicial referrals\") +\n  theme_minimal()\n```\n:::\n\n\n:::::\n\n::: {.callout-tip collapse=\"true\"}\n## Corollary: Residual Balance\n\nClaim: the average of the residuals is zero\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(liquor_df$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.819017e-13\n```\n\n\n:::\n:::\n\n\n:::\n\n\n# Sorting\n\n::::: {.panel-tabset}\n\n## arrange\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   LLV predictions   residuals\n1  262    97.80000 -164.200000\n2  129    51.60000  -77.400000\n3  103    61.86667  -41.133333\n4   54    56.73333    2.733333\n5   50    67.00000   17.000000\n6   57    92.66667   35.666667\n7   49    87.53333   38.533333\n8   15    72.13333   57.133333\n9   18    82.40000   64.400000\n10  10    77.26667   67.266667\n```\n\n\n:::\n:::\n\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  select(LLV, predictions, residuals) |>\n  arrange(residuals)\n```\n:::\n\n:::\n\n::::\n\n## desc\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   LLV predictions   residuals\n1   10    77.26667   67.266667\n2   18    82.40000   64.400000\n3   15    72.13333   57.133333\n4   49    87.53333   38.533333\n5   57    92.66667   35.666667\n6   50    67.00000   17.000000\n7   54    56.73333    2.733333\n8  103    61.86667  -41.133333\n9  129    51.60000  -77.400000\n10 262    97.80000 -164.200000\n```\n\n\n:::\n:::\n\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  select(LLV, predictions, residuals) |>\n  arrange(desc(residuals))\n```\n:::\n\n:::\n\n::::\n\n## head\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  LLV predictions residuals\n1  10    77.26667  67.26667\n2  18    82.40000  64.40000\n3  15    72.13333  57.13333\n4  49    87.53333  38.53333\n```\n\n\n:::\n:::\n\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  select(LLV, predictions, residuals) |>\n  arrange(desc(residuals)) |>\n  head(4)\n```\n:::\n\n:::\n\n::::\n\n## tail\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   LLV predictions   residuals\n7   54    56.73333    2.733333\n8  103    61.86667  -41.133333\n9  129    51.60000  -77.400000\n10 262    97.80000 -164.200000\n```\n\n\n:::\n:::\n\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nliquor_df |>\n  select(LLV, predictions, residuals) |>\n  arrange(desc(residuals)) |>\n  tail(4)\n```\n:::\n\n:::\n\n::::\n\n:::::\n\n::: {.callout-warning}\n# DCP2\n:::\n\n# Ordinary Least Squares\n\n::: {.callout-note}\n## OLS\n\n*Idea*: The *best-fit* line is where the **sum-of-squared residuals** is minimized.\n\n$$E(a,b) = \\sum_{i=1}^{n} (y_{i} - a - bx_{i})^{2}$$\n\n**Claim**: $$a = \\frac{ (\\sum y_{i})(\\sum x_{i}^{2}) - (\\sum x_{i})(\\sum x_{i}y_{i}) }{ n\\sum x_{i}^{2} - (\\sum x_{i})^{2} }, \\quad b = \\frac{ n\\sum x_{i}y_{i} - (\\sum x_{i})(\\sum y_{i}) }{ n\\sum x_{i}^{2} - (\\sum x_{i})^{2} }$$\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## (optional) Proof\n\nSearch for a critical point by setting the partial derivatives (along with the Chain Rule) equal to zero.\n\n$$0 = \\frac{\\partial E}{\\partial a} = -2\\sum_{i = 1}^{n} (y_{i} - a - bx_{i}) = 2an + 2b\\sum_{i = 1}^{n}x_{i} - 2\\sum_{i = 1}^{n} y_{i}$$\n$$0 = \\frac{\\partial E}{\\partial b} = -2\\sum_{i = 1}^{n} (y_{i} - a - bx_{i})x_{i} = 2a\\sum_{i = 1}^{n}x_{i} + 2b\\sum_{i = 1}^{n}x_{i}^{2} - 2\\sum_{i = 1}^{n} x_{i}y_{i}$$\n\nCreate a matrix system of equations.\n\n$$\\left[  \\begin{array}{cc}\n  n & \\sum_{i = 1}^{n}x_{i} \\\\\n  \\sum_{i = 1}^{n}x_{i} & \\sum_{i = 1}^{n}x_{i}^{2} \\\\\n  \\end{array}\\right]\n  \\left[  \\begin{array}{c}  a \\\\ b \\end{array}\\right]\n  =\n  \\left[  \\begin{array}{c}  \\sum_{i = 1}^{n} y_{i} \\\\ \\sum_{i = 1}^{n} x_{i}y_{i} \\end{array}\\right]\n  $$\n\n\nEmploy a matrix inverse.\n\n$$\\begin{array}{rcl}\n  \\left[  \\begin{array}{c}  a \\\\ b \\end{array}\\right] & = & \n  \\left[  \\begin{array}{cc}\n  n & \\sum_{i = 1}^{n}x_{i} \\\\\n  \\sum_{i = 1}^{n}x_{i} & \\sum_{i = 1}^{n}x_{i}^{2} \\\\\n  \\end{array}\\right]^{-1}\\left[  \\begin{array}{c}  \\sum_{i = 1}^{n} y_{i} \\\\ \\sum_{i = 1}^{n} x_{i}y_{i} \\end{array}\\right] \\\\\n  \n  ~ & ~ & ~ \\\\\n  \n  \\left[  \\begin{array}{c}  a \\\\ b \\end{array}\\right] & = & \\frac{1}{n\\sum x_{i}^{2} - (\\sum x_{i})^{2}} \\left[  \\begin{array}{cc}\n  \\sum_{i = 1}^{n}x_{i}^{2} & -\\sum_{i = 1}^{n}x_{i} \\\\\n  -\\sum_{i = 1}^{n}x_{i} & n \\\\\n  \\end{array}\\right]  \\left[  \\begin{array}{c}  \\sum_{i = 1}^{n} y_{i} \\\\ \\sum_{i = 1}^{n} x_{i}y_{i} \\end{array}\\right] \\\\\n  \n  ~ & ~ & ~ \\\\\n  \n  \\left[  \\begin{array}{c}  a \\\\ b \\end{array}\\right] & = & \\frac{1}{n\\sum x_{i}^{2} - (\\sum x_{i})^{2}} \n  \\left[  \\begin{array}{c}  (\\sum y_{i})(\\sum x_{i}^{2}) - (\\sum x_{i})(\\sum x_{i}y_{i}) \\\\  n\\sum x_{i}y_{i} - (\\sum x_{i})(\\sum y_{i}) \\end{array}\\right] \\\\\n\\end{array}$$\n\nThis is the **method of least squares**\n\n:::\n\n# Linear Model in R\n\n$$\\hat{y} = a + bx$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_fit <- lm(LLV ~ year, data = liquor_df)\nprint(lin_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = LLV ~ year, data = liquor_df)\n\nCoefficients:\n(Intercept)         year  \n -10286.933        5.133  \n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Interpret the Slope\n\n\n::: {.cell}\n\n:::\n\n\nFor every increase in year, the number of judicial referrals increasing by about 5.13 referrals.\n\n:::\n\n\n\n## Prediction\n\nPredict the number of judicial referrals for liquor law violations in the year 2024.\n\n::: {.callout-tip}\n## Write a math expression ...\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n-10286.933 + (5.133)x\n```\n\n\n:::\n:::\n\n\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mathematically\na <- summary(lin_fit)$coefficients[1]\nb <- summary(lin_fit)$coefficients[2]\n\na + b*(2024)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n102.9333\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# properly programmatically\npredict(lin_fit, newdata = data.frame(year = 2024))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n102.9333\n```\n\n\n:::\n:::\n\n\n# Determination\n\nWe want a measurement that can assure us of *how useful* a model will be for predictions.\n\n::: {.callout-note}\n## Coefficient of determination\n\nThe **coefficient of determination** is defined as\n\n$$R^{2} = \\frac{\\text{explained variance}}{\\text{total variance}}$$\n\nFor analysis of variance:\n\n* explained variation: $\\sum(\\hat{y} - \\bar{y})^{2}$\n* unexplained variation: $\\sum(y - \\hat{y})^{2}$\n* total variation = explained variation + unexplained variation\n$$\\sum(y - \\bar{y})^{2} = \\sum(\\hat{y} - \\bar{y})^{2} + \\sum(y - \\hat{y})^{2}$$\n\n:::\n\n## Inference\n\nWhy is that denoted \"$R^2$\"? For linear regression, the coefficient of determination is literally the square of the correlation coefficient ($r$)\n\n* correlation $-1 \\leq r \\leq 1$ implies coefficient of determination\n$$0 \\leq R^{2} \\leq 1$$\n* want more \"explained variation\", thus higher $R^{2}$ means a better model\n\n## Guidelines\n\n:::: {.columns}\n\n::: {.column width=\"60%\"}\nIn this course, we will simply follow the Pearson suggestions for interpreting coefficient of determination values:\n\n* $0 \\leq R^{2} < 0.4$: poor model\n* $0.4 \\leq R^{2} < 0.7$: good model\n* $0.7 \\leq R^{2} \\leq 1.0$: great model\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"30%\"}\n![Karl Pearson](Karl_Pearson.png)\n:::\n\n::::\n\n## Model Statistics\n\nIn `R`, we can use `summary` to access **model statistics**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lin_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = LLV ~ year, data = liquor_df)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-67.27 -52.48 -26.33  30.17 164.20 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)\n(Intercept) -10286.933  17504.409  -0.588    0.573\nyear             5.133      8.672   0.592    0.570\n\nResidual standard error: 78.77 on 8 degrees of freedom\nMultiple R-squared:  0.04196,\tAdjusted R-squared:  -0.07779 \nF-statistic: 0.3504 on 1 and 8 DF,  p-value: 0.5702\n```\n\n\n:::\n:::\n\n\n## Multiple R-Squared\n\n::: {.callout-note}\n### Sum of Squares\n\nThe coefficient of determination can be a measure of how much better `model2` is than `model1` (later: model selection).\n\n$$R^{2} = \\frac{\\text{SSR}(\\text{model1}) - \\text{SSR}(\\text{model2})}{\\text{SSR}(\\text{model1})}$$\n:::\n\n::: {.callout-tip}\n### Baseline\n\nIn this example (liquor law violations), we could treat $\\bar{y}$, the average of the output data, as a *baseline* and see if the linear regression model leads to better predictions.\n\n$$R^{2} = \\frac{\\text{SSR}(\\text{mean}) - \\text{SSR}(\\text{line})}{\\text{SSR}(\\text{mean})}$$\n:::\n\n::::: {.panel-tabset}\n\n### Calculation\n\n$$\\begin{array}{rcccl}\n  \\text{SSR}(\\text{mean}) & = & \\sum_{i=0}^{n}\\left(y - \\bar{y}\\right)^{2} & \\approx & 51808 \\\\\n  \\text{SSR}(\\text{line}) & = & \\sum_{i=0}^{n}\\left(y - \\hat{y}\\right)^{2} & \\approx & 49634 \\\\\n  R^{2} & = & \\frac{\\text{SSR}(\\text{mean}) - \\text{SSR}(\\text{line})}{\\text{SSR}(\\text{mean})} & \\approx & 0.04196\n\\end{array}$$\n\n### code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyhat <- mean(liquor_df$LLV, na.rm = TRUE)\ndeviations <- liquor_df$LLV - yhat\n\nlin_fit <- lm(LLV ~ year, data = liquor_df)\npredictions <- predict(lin_fit,\n                      newdata = data.frame(year = liquor_df$year))\nresiduals <- liquor_df$LLV - predictions\n\nSSR_mean <- sum(deviations * deviations)\nSSR_line <- sum(residuals * residuals)\n\nR_squared <- (SSR_mean - SSR_line) / SSR_mean\ncat(round(R_squared, 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.04196\n```\n\n\n:::\n:::\n\n\n:::::\n\n::: {.callout-warning}\n## Interpreting Multiple R-Squared\n\nIn this example, with the small value\n\n$$R^{2} \\approx 0.04196$$\n\nthe linear regression model was barely better than simply reporting the average output value.\n:::\n\n\n## Adjusted R-Squared\n\n::: {.callout-note}\n### Adjusting for Degrees of Freedom\n\nHere in SML 201, we will use the \"Adjusted R-squared\" value that accounts for the number of predictor variables (later: degrees of freedom), and then look for the highest adjusted R-squared values.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lin_fit)$adj.r.squared #negative result??\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.07779285\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n### Interpreting Adjusted R-Squared\n\nIn this example, with the *negative* value\n\n$$R^{2} \\approx -0.07779$$\n\nthe linear regression model was *worse* than simply reporting the average output value.\n:::\n\n\n\n# Historical Example\n\n## Francis Galton\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n![Sir Francis Galton](Francis_Galton.png)\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n* 1822 - 1911\n* cousin of Charles Darwin\n* correlation discovery\n\n    * 1846: August Bravais\n    * 1888: Francis Galton\n:::\n\n::::\n\n## Do tall parents have tall children?\n\nThe `Galton` data set in the `HistData` package has two variables\n\n* parents' height (see documentation for weighted formula)\n* child's height\n\nfor about 200 families\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheredity_df <- HistData::Galton\n```\n:::\n\n\n## Scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_fit <- lm(child ~ parent, data = heredity_df)\na <- summary(lin_fit)$coefficients[1]\nb <- summary(lin_fit)$coefficients[2]\n\nheredity_df |>\n  ggplot(aes(x = parent, y = child)) +\n  geom_point() +\n  geom_smooth(formula = \"y ~ x\", method = \"lm\", se = FALSE) +\n  labs(title = \"Do tall parents have tall children?\",\n       subtitle = paste0(\"y = \", round(a, 4), \" + \", round(b, 4), \"x\"),\n       caption = \"Source: Galton Survey of Heights\",\n       x = \"parent's heights (weighted average)\",\n       y = \"child's height\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n## Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_fit <- lm(child ~ parent, data = heredity_df)\n\nprint(lin_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = child ~ parent, data = heredity_df)\n\nCoefficients:\n(Intercept)       parent  \n    23.9415       0.6463  \n```\n\n\n:::\n:::\n\n\nFor every one inch increase in parents' height, the child's height increases by about 0.65 inches.\n\n## Determination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lin_fit)$adj.r.squared #still a bad model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2096103\n```\n\n\n:::\n:::\n\n\n\n## Prediction\n\nIf the parents are 70 inches in height, what do we predict for the height of the child?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(lin_fit, newdata = data.frame(parent = 70))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n69.18187 \n```\n\n\n:::\n:::\n\n\nIf the parents are 58 inches in height, what do we predict for the height of the child?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(lin_fit, newdata = data.frame(parent = 58))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n61.42638 \n```\n\n\n:::\n:::\n\n\n## Legacy\n\n::: {.callout-warning}\n### Regression to the Mean\n\nIn these early studies of heredity, Galton coined the phrase\n\n$$\\text{regression to the mean}$$\n\nand similar calculations have been called *regression* ever since.\n:::\n\n::: {.callout-warning}\n# DCP3\n:::\n\n\n\n# Chemistry Example\n\n## Michaelis and Menton\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n![Leonor Michaelis and Maud Menton](Michaelis_Menton.png)\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\nLeonor Michaelis\n\n* Berlin University (1897)\n\nMaud Menton\n\n* University of Toronto (1911)\n\n*Die Kinetik der Invertinwirkung* (1913)\n\n$$v = \\frac{V_{\\text{max}}[S]}{K_{m} + [S]}$$\n\n* $v$: reaction rate (micromolars per minute)\n* $[S]$: substrate concentration (micromolars)\n\n:::\n\n::::\n\n## Enzyme Kinetics\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n![Essential Cell Biology](Alberts_cell_bio.png)\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"70%\"}\nThe reaction rates of the reaction S $\\rightarrow$ P catalyzed by enzyme E were determined under conditions such that only very little product was formed.  Compute the maximum reaction velocity asymptote $V_{\\text{max}}$ and the Michaelis-Menton constant $K_{m}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qqldxeprlw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qqldxeprlw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qqldxeprlw thead, #qqldxeprlw tbody, #qqldxeprlw tfoot, #qqldxeprlw tr, #qqldxeprlw td, #qqldxeprlw th {\n  border-style: none;\n}\n\n#qqldxeprlw p {\n  margin: 0;\n  padding: 0;\n}\n\n#qqldxeprlw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qqldxeprlw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qqldxeprlw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qqldxeprlw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qqldxeprlw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qqldxeprlw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qqldxeprlw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qqldxeprlw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qqldxeprlw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qqldxeprlw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qqldxeprlw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qqldxeprlw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qqldxeprlw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qqldxeprlw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qqldxeprlw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qqldxeprlw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qqldxeprlw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qqldxeprlw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qqldxeprlw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qqldxeprlw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qqldxeprlw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qqldxeprlw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qqldxeprlw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qqldxeprlw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qqldxeprlw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qqldxeprlw .gt_left {\n  text-align: left;\n}\n\n#qqldxeprlw .gt_center {\n  text-align: center;\n}\n\n#qqldxeprlw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qqldxeprlw .gt_font_normal {\n  font-weight: normal;\n}\n\n#qqldxeprlw .gt_font_bold {\n  font-weight: bold;\n}\n\n#qqldxeprlw .gt_font_italic {\n  font-style: italic;\n}\n\n#qqldxeprlw .gt_super {\n  font-size: 65%;\n}\n\n#qqldxeprlw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qqldxeprlw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qqldxeprlw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qqldxeprlw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qqldxeprlw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qqldxeprlw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qqldxeprlw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qqldxeprlw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qqldxeprlw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\" style>Michaelis Menton Experiment</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>reaction rate vs substrate concentration</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"S\">S</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"v\">v</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">0.08</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">0.15</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">0.12</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">0.21</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">0.54</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">0.70</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">1.23</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">1.10</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">1.82</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">1.30</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">2.72</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">1.50</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">4.94</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">1.70</td></tr>\n    <tr><td headers=\"S\" class=\"gt_row gt_center\" style=\"background-color: #FFC100;\">10.00</td>\n<td headers=\"v\" class=\"gt_row gt_center\" style=\"background-color: #D0CEF3;\">1.80</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"> Die Kinetik der Invertinwirkung</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n\n::::\n\n## Scatterplot\n\n* reaction rate (lower case v)\n* substrate concentration (capital S)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMM_df |>\n  ggplot(aes(x = S, y = v)) +\n  geom_smooth(formula = \"y ~ x\", method = \"loess\", se = TRUE) +\n  geom_point(color = \"black\", size = 4) +\n  labs(title = \"Michaelis Menton Enzyme Kinetics Experiment\",\n       subtitle = \"reaction rate vs substrate concentration\",\n       caption = \"Essential Cell Biology\",\n       x = \"substrate concentration (micromolars)\",\n       y = \"reaction rate (micromolars per minute)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n## Transformation\n\n[Hans Lineweaver](https://carnotcycle.wordpress.com/2014/12/02/the-michaelis-menten-equation/) (George Washington Univ., 1934)\n\n$$v = \\frac{V_{\\text{max}}[S]}{K_{m} + [S]} \\quad\\rightarrow\\quad \\frac{1}{v} = \\frac{K_{m}}{V_{\\text{max}}} \\cdot \\frac{1}{[S]} + \\frac{1}{V_{\\text{max}}}$$\n\nThe reciprocal of the reaction rate is *linear* with respect to the reciprocal of the substrate concentration.\n\n## Double-Reciprocal Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMM_df <- MM_df |>\n  mutate(rS = 1/S,\n         rv = 1/v)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMM_df |>\n  ggplot(aes(x = rS, y = rv)) +\n  geom_smooth(formula = \"y ~ x\", method = \"lm\", se = FALSE) +\n  geom_point(color = \"black\", size = 4) +\n  labs(title = \"Michaelis Menton Enzyme Kinetics Experiment\",\n       subtitle = \"Double Reciprocal Plot\",\n       caption = \"Essential Cell Biology\",\n       x = \"1/[S] (1/micromoles)\",\n       y = \"1/v (minutes per micromolar)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n## Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_fit <- lm(rv ~ rS, data = MM_df)\n```\n:::\n\n\n## Determination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lin_fit)$adj.r.squared #great model!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9995051\n```\n\n\n:::\n:::\n\n\n## Extracting the Constants\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslope <- lin_fit$coefficients[2]\nintercept <- lin_fit$coefficients[1]\n\nVmax <- 1/intercept\nKm <- slope * Vmax\n\nprint(paste(\"The Vmax asymptote is \", Vmax))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The Vmax asymptote is  1.9894653306508\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"The Michaelis-Menton constant is \", Km))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The Michaelis-Menton constant is  0.991986524114476\"\n```\n\n\n:::\n:::\n\n\n## MM Experiment Revisited\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMM_df |>\n  ggplot(aes(x = S, y = v)) +\n  geom_smooth(formula = \"y ~ x\", method = \"loess\", se = TRUE) +\n  geom_point(color = \"black\", size = 4) +\n  geom_abline(slope = Km, intercept = 0, color = \"red\") +\n  geom_abline(slope = 0, intercept = Vmax, color = \"purple\") +\n  labs(title = \"Michaelis Menton Enzyme Kinetics Experiment\",\n       subtitle = \"maximum reaction velocity asymptote (purple)\\nMichaelis-Menton constant (red slope)\",\n       caption = \"Essential Cell Biology\",\n       x = \"substrate concentration (micromolars)\",\n       y = \"reaction rate (micromolars per minute)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_linear_regression_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n# Quo Vadimus?\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n* This week: Precept 4\n* Project 1 due: Feb 24\n* Exam 1: March 5\n* Refer to weekly announcement for more info\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n![coefficient of determination](xkcd_1725.png)\n\n* image source: [XKCD](https://xkcd.com/1725/)\n:::\n\n::::\n\n\n# Footnotes\n\n::: {.callout-note collapse=\"true\"}\n## (optional) Additional Resources\n\n* Charles Darwin's grandfather invented the [buy one get one free deal](https://en.wikipedia.org/wiki/Josiah_Wedgwood) to sell more pottery\n\nsubmitted \n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.4 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4    \n [5] purrr_1.1.0     readr_2.1.5     tidyr_1.3.1     tibble_3.3.0   \n [9] ggplot2_4.0.0   tidyverse_2.0.0 HistData_1.0.0  gt_1.0.0       \n\nloaded via a namespace (and not attached):\n [1] Matrix_1.7-4       gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2    \n [5] tidyselect_1.2.1   xml2_1.3.8         splines_4.5.2      scales_1.4.0      \n [9] yaml_2.3.10        fastmap_1.2.0      lattice_0.22-7     R6_2.6.1          \n[13] labeling_0.4.3     generics_0.1.4     knitr_1.50         htmlwidgets_1.6.4 \n[17] pillar_1.11.0      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.1.6       \n[21] stringi_1.8.7      xfun_0.52          sass_0.4.10        S7_0.2.0          \n[25] viridisLite_0.4.2  timechange_0.3.0   cli_3.6.5          mgcv_1.9-3        \n[29] withr_3.0.2        magrittr_2.0.3     digest_0.6.37      grid_4.5.2        \n[33] rstudioapi_0.17.1  hms_1.1.3          nlme_3.1-168       lifecycle_1.0.4   \n[37] vctrs_0.6.5        evaluate_1.0.4     glue_1.8.0         farver_2.1.2      \n[41] rmarkdown_2.29     tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.8.1 \n```\n\n\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n::::: {.panel-tabset}\n\n\n\n:::::",
    "supporting": [
      "07_linear_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}