{
  "hash": "0a850a15a94fc26fd3763b6c9f452995",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"14: Confidence Intervals\"\nauthor: \"Derek Sollberger\"\ndate: \"2026-03-24\"\nformat:\n  html:\n    toc: true\n    theme: cerulean\n---\n\n# SML 201\n\n::: {.callout-note collapse=\"true\"}\n## Libraries and Helper Functions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"bayesrules\") #data set: Pulse of the Nation\nlibrary(\"ggimage\")    #customize images for scatterpoint points\nlibrary(\"ggtext\")     #adorn ggplot text\nlibrary(\"gt\")         #great tables\nlibrary(\"infer\")      #streamlined code for inference tasks\nlibrary(\"janitor\")    #compute proportions easily\nlibrary(\"tidyverse\")  #tools for data wrangling and visualization\n\n# school colors\nprinceton_orange <- \"#E77500\"\nprinceton_black  <- \"#121212\"\n\n# data set: Pulse of the Nation\ndata(pulse_of_the_nation)\npulse_df <- pulse_of_the_nation\n\n# data set: SML 201 demographics survey\ndemo_df <- readr::read_csv(\"demographics_data.csv\")\n\n# data set: SML 201 probability perceptions survey\nprob_df <- readr::read_csv(\"probability_perceptions.csv\")\n\n# Derek's helper functions\nsource(\"vdist.R\")\n```\n:::\n\n\n\n\n:::\n\n## Start\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n* **Goal**: Estimate unknown population statistics\n\n* **Objective**: Deploy and interpret confidence intervals\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"40%\"}\n![Ghostbusters (1984)](ghostbusters_1984_movie_poster.png)\n:::\n\n::::\n\n# Old Methods\n\n## Scenario: Believe in Ghosts?\n\n::::: {.panel-tabset}\n\n## Query\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n![Ray Stantz](Ray_Stantz.png)\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\nWhat proportion of people believe that ghosts exist?\n:::\n\n::::\n\n## Data\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* source: [Pulse of the Nation](https://thepulseofthenation.com/#intro) survey by Cards Against Humanity\n* Poll 1: September 2017\n\n* 1000 observations\n* 15 variables\n\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n![Pulse of the Nation](pulse_of_the_nation.png)\n:::\n\n::::\n:::::\n\n\n## Normal Distribution\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n![](Walter_Peck.png)\t\nWalter Peck wants estimates to have at least *95 percent confidence*!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2.5 and 97.5 percentiles\nqnorm(c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.959964  1.959964\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvnorm(qnorm(c(0.025, 0.975)), section = \"between\") +\n  annotate(\"text\", x = 0, y = 0.2, label = \"95%\", \n           color = \"white\", size = 15) +\n  labs(title = \"Extracting a 95 Percent Interval\",\n       x = \"z\") +\n  scale_x_continuous(breaks = c(-1.96, 1.96),\n                     labels = c(-1.96, 1.96))\n```\n\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Sample Proportion\n\n::::: {.panel-tabset}\n\n## Display\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n ghosts    n percent\n     No  621   62.1%\n    Yes  379   37.9%\n  Total 1000  100.0%\n```\n\n\n:::\n:::\n\n\n$$\\hat{p} = 0.379$$\n$$n = 1000$$\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulse_df |>\n  tabyl(ghosts) |>\n  adorn_totals(\"row\") |>\n  adorn_pct_formatting()\n\ntitle_string <- \"<span style = 'color:#23b63c'>Believes that Ghosts Exist</span><br>versus<br><span style = 'color:#ea0000'>Doesn't Believe that Ghosts Exist</span>\"\n\npulse_df |>\n  ggplot() +\n  geom_bar(aes(x = ghosts, fill = ghosts)) +\n  annotate(\"text\", x = c(\"No\", \"Yes\"), y = c(310, 170), \n           label = c(\"62%\", \"38%\"), \n           color = \"white\", size = 15) +\n  labs(title = title_string,\n       caption = \"SML 201\") +\n  scale_fill_manual(values = c(\"#ea0000\", \"#23b63c\")) +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        plot.title = element_markdown(hjust = 0.5,\n                                      face = \"bold\",\n                                      size = 20))\n```\n:::\n\n\n:::::\n\n\n## Confidence Interval for a Proportion\n\n::::: {.panel-tabset}\n\n## Math\n\n$$\\hat{p} \\pm E, \\quad\\text{where } E = z_{\\alpha/2}*\\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n}} \\text{ and } z_{\\alpha/2} \\approx 1.96$$\n\n$$\\left(0.3489, 0.4091\\right)$$\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sample statistics\nphat <- mean(pulse_df$ghosts == \"Yes\")\nn <- sum(!is.na(pulse_df$ghosts))\n\n# margin of error\nE <- qnorm(0.975)*sqrt((phat*(1-phat))/n)\n\n# confidence interval\nphat + c(-1,1)*E\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3489314 0.4090686\n```\n\n\n:::\n:::\n\n\n:::::\n\n::: {.callout-note}\n## Inference Interpretation\n\n*We are 95 percent confident* that the **true population proportion** of Americans that believe in ghosts is in between 34.89 and 40.91 percent.\n:::\n\n::: {.callout-warning}\n## DCP1\n:::\n\n## Scenario: How Old Are You?\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n![Dana Barrett](Dana_Barrett.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\nAmong the people that believe in ghosts, how old are you?\n:::\n\n::::\n\n\n::::: {.panel-tabset}\n\n## Display\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  ghosts  xbar     n\n  <fct>  <dbl> <int>\n1 No      50.3   621\n2 Yes     48.0   379\n```\n\n\n:::\n:::\n\n\n$$\\bar{x} \\approx 47.9525$$\n$$n = 379$$\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulse_df |>\n  group_by(ghosts) |>\n  summarize(xbar = mean(age, na.rm = TRUE),\n            n = n())\n\ntitle_string <- \"<span style = 'color:#23b63c'>Believes that Ghosts Exist</span><br>versus<br><span style = 'color:#ea0000'>Doesn't Believe that Ghosts Exist</span>\"\n\npulse_df |>\n  ggplot() +\n  geom_density(aes(x = age, fill = ghosts),\n               alpha = 0.5) +\n  labs(title = title_string,\n       caption = \"SML 201\") +\n  scale_fill_manual(values = c(\"#ea0000\", \"#23b63c\")) +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        plot.title = element_markdown(hjust = 0.5,\n                                      face = \"bold\",\n                                      size = 20))\n```\n:::\n\n\n:::::\n\n\n## Confidence Interval for a Mean\n\n::::: {.panel-tabset}\n\n## Math\n\n$$\\bar{x} \\pm E, \\quad\\text{where } E = t_{\\alpha/2}*\\frac{s}{\\sqrt{n}}$$\n\n$$\\left(46.3651, 49.5399\\right)$$\n\n*We are 95 percent confident* that the **true population mean** age for people that believe ghosts exist is in between 46.37 and 49.54 years old.\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# subset\nghosts_yes <- pulse_df |> filter(ghosts == \"Yes\")\n\n# sample statistics\nxbar <- mean(ghosts_yes$age, na.rm = TRUE)\ns <- sd(ghosts_yes$age, na.rm = TRUE)\nn <- sum(!is.na(ghosts_yes$age))\n\n# margin of error (here: \"df\" are degrees of freedom)\nE <- qt(0.975, df = n - 1)*s/sqrt(n)\n\n# confidence interval\nxbar + c(-1,1)*E\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 46.36511 49.53991\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Inference Interpretation\n\n*We are 95 percent confident* that the **true population mean** age for people that believe ghosts exist is in between 46.37 and 49.54 years old.\n:::\n\n\n:::::\n\n## Student t Distribution\n\n::::: {.panel-tabset}\n\n## Idea\n\nThe **Student t distribution** is an abstraction of the standard normal distribution that adjusts with wider tails to allow for more probability in the tails\n\n![t distribution](t_distribution_bell_curves.png)\n\n## Gosset\n\n![William Sealy Gosset](William_Sealy_Gosset.png)\n\n## df\n\nIn advanced statistics, such as the adjusted $R^{2}$ calculation for the coefficient of determination, the **degrees of freedom** are the difference between\n\n* number of observations in the data\n* number of independent variables being modeled\n\nFor this setting---estimating the true population mean---the degrees of freedom are simply\n\n$$df = n - 1$$\n:::::\n\n::: {.callout-warning}\n## Leaving the t distribution behind\n\nFor these calculations\n\n$$\\bar{x} \\pm E, \\quad\\text{where } E = t_{\\alpha/2}*\\frac{s}{n}$$\n\n* rely more on *summary statistics* rather than all of the gathered data\n* \"degrees of freedom\" is a rather convoluted notion\n* t-distribution is itself an approximation\n* leads to more reliance on abstract probability distributions\n* departs from frequentist probability philosophy\n* more useful before calculators and computers\n:::\n\n\n# Modern Methods\n\n::: {.callout-tip}\n## infer\n\nThe developers of the `infer` package (and similar in other programming languages) streamlined coding syntax for these statistical tasks\n\n* eases programming\n* leverages *simulations*\n:::\n\n\n## Scenario: Princeton Politics\n\nThe survey question was\n\n> On a scale of 0 to 100---with 0 = Democrat and 100 = Republican---where are your political leanings? \n\n### Bootstrap Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(201)\nbootstrap_distribution <- demo_df |>\n  specify(response = politics) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"mean\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 29 rows containing missing values.\n```\n\n\n:::\n:::\n\n\n### Endpoints (Standard Error)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(demo_df$politics, na.rm = TRUE)\nse_ci <- bootstrap_distribution |>\n  get_confidence_interval(level = 0.95,\n                          type = \"se\", \n                          point_estimate = xbar)\n```\n:::\n\n\n### Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_distribution |>\n  visualize() +\n  shade_confidence_interval(endpoints = se_ci,\n                            color = princeton_black,\n                            fill = princeton_orange) +\n  labs(title = \"Political Leanings of Princeton Students\",\n       subtitle = \"Spring 2026\",\n       caption = \"SML 201\",\n       x = \"0: Democrat ... 100: Republican\") +\n  theme_minimal() +\n  xlim(0, 100)\n```\n\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n### Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(round(se_ci))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1       26       35\n```\n\n\n:::\n:::\n\n\nIn this survey question, \"On a scale of 0 to 100---with 0 = Democrat and 100 = Republican---where are your political leanings?\", *we are 95 percent confident* that the true population mean for Princeton students is in between 26 and 35.\n\n::: {.callout-caution}\n### Discussion\n\nThis was a survey among SML 201 students\n\n* not a representative or random sample of Princeton students\n* self-reported data\n:::\n\n::: {.callout-warning}\n## DCP2\n:::\n\n## Scenario: Pineapple on Pizza\n\nThe sample proportions (among those who were adamant) were\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemo_df |>\n  filter(pineapple_pizza %in% c(\"No!\", \"Yes!\")) |>\n  tabyl(pineapple_pizza) |>\n  adorn_totals(\"row\") |>\n  adorn_pct_formatting()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pineapple_pizza   n percent\n             No!  49   46.2%\n            Yes!  57   53.8%\n           Total 106  100.0%\n```\n\n\n:::\n:::\n\n\n### Bootstrap Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(201)\nbootstrap_distribution <- demo_df |>\n  \n  # make into factor (categorical) variable if need be\n  # mutate(pineapple_pizza = factor(pineapple_pizza)) |>\n  \n  filter(pineapple_pizza %in% c(\"No!\", \"Yes!\")) |>\n  specify(response = pineapple_pizza, success= \"Yes!\") |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"prop\")\n```\n:::\n\n\n### Endpoints (Percentile)\n\nBuilding the confidence interval from percentiles is perhaps more reasonable than using the standard errors (and less code too).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nper_ci <- bootstrap_distribution |>\n  get_ci(level = 0.95, type = \"percentile\")\n```\n:::\n\n\n### Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_distribution |>\n  visualize() +\n  shade_ci(per_ci, \n           color = princeton_black, fill = princeton_orange)\n```\n\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_distribution |> get_ci()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    0.443    0.632\n```\n\n\n:::\n\n```{.r .cell-code}\n# default settings: 95% confidence, percentile method\n```\n:::\n\n\n::: {.callout-note}\n### Inference Interpretation\n\nAmong the Princeton students who have a strong opinion on whether or not pineapple is a good pizza topping, *we are 95 percent confident* that the *true population proportion* of students who like pineapple on pizza is in between 44 and 63 percent. \n:::\n\n\n::: {.callout-caution}\n### Discussion\n\nThis was a survey among SML 201 students\n\n* relatively smaller sample size ($n = 106$ students had a stated preference)\n* Since 0.5 is contained within the confidence interval, this result is not significally different than simply flipping a fair coin.\n:::\n\n\n# Theory\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n![Peter Venkman](Peter_Venkman.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\nBut why are we using careful language like \"We are 95 percent confident ...\"?\n:::\n\n::::\n\n## Scenario: 20 Ghosts\n\n:::: {.columns}\n\n::: {.column width=\"25%\"}\n![Louis Tully](Louis_Tully.png)\n:::\n\n::: {.column width=\"5%\"}\n\t\n:::\n\n::: {.column width=\"40%\"}\nRemember when we faced the **Dungeon Master** and their army of 20 ghosts?  Under the equal probabilities of a uniform distribution, we knew that we would face off against $\\mu = 10.5$ ghosts, on average.\t\n:::\n\n::: {.column width=\"5%\"}\n\t\n:::\n\n::: {.column width=\"25%\"}\n![d20](d20_die.png)\n:::\n\n::::\n\n### Experiment\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n![Egon Spengler](Egon_Spengler.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"60%\"}\nWe could *resample* the outcome space and see what proportion of confidence intervals capture the [population mean] ghost.\n:::\n\n::::\n\n### Simulation\n\n::::: {.panel-tabset}\n\n#### Animation\n\n\n::: {.cell}\n\n:::\n\n![CI animation](CI_animation.gif)\n\n#### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(201)\n# d20\nd20_df <- data.frame(d20_outcomes = 1:20)\n\n# create data frame and allocate space\ndf_for_graph <- data.frame(\n  id = 1:26,\n  a = rep(NA, 26),\n  b = rep(NA, 26),\n  result = rep(NA, 26),\n  result_color = rep(NA, 26)\n)\n\nfor(i in 1:26){\n  # bootstrap_distribution <- d20_df |>\n  #   specify(response = d20_outcomes) |>\n  #   generate(reps = 50, type = \"bootstrap\") |>\n  #   calculate(stat = \"mean\")\n  # CI <- bootstrap_distribution |> get_ci()\n  \n  this_sample <- sample(1:20, size = 10, replace = TRUE)\n  xbar <- mean(this_sample)\n  s <- sd(this_sample)\n  n <- length(this_sample)\n  E <- qt(0.975, df = n-1)*s/sqrt(n)\n  \n  \n  # df_for_graph$a[i] <- unlist(CI[1])\n  # df_for_graph$b[i] <- unlist(CI[2])\n  df_for_graph$a[i] <- xbar - E\n  df_for_graph$b[i] <- xbar + E\n  df_for_graph$result[i] <- ifelse(\n    df_for_graph$a[i] < 10.5 & 10.5 < df_for_graph$b[i],\n    \"captured\",\n    \"not captured\"\n  )\n  df_for_graph$result_color[i] <- ifelse(\n    df_for_graph$a[i] < 10.5 & 10.5 < df_for_graph$b[i],\n    \"#23b63c\",\n    \"#ea0000\"\n  )\n  \n  capture_rate <- mean(df_for_graph$result == \"captured\",\n                       na.rm = TRUE)\n  \n  this_plot <- df_for_graph |>\n    filter(id %in% 1:i) |>\n    ggplot() +\n    # geom_vline(aes(xintercept = 10.5), \n    #            color = \"#ab9f8f\", linewidth = 2) +\n    geom_segment(aes(x = a, y = id, \n                     xend = b, yend = id,\n                     color = result_color)) +\n    geom_point(aes(x = a, y = id, color = result_color),\n               size = 3) +\n    geom_point(aes(x = b, y = id, color = result_color),\n               size = 3) +\n    geom_image(aes(x = 10.5, y = id),\n               image = \"ghostbusters_ghost.png\") +\n    labs(title = \"Confidence Intervals\",\n         subtitle = paste0(\"capture rate: \",\n                           round(100*capture_rate, 2),\n                           \" percent\"),\n         caption = \"SML 201\",\n         x = \"ghosts\", y = \"interval number\") +\n    scale_color_manual(values = c(\"#23b63c\", \"#ea0000\")) +\n    theme_minimal() +\n    theme(legend.position = \"none\")\n  \n  ggsave(paste0(\"images/CI_plot\", LETTERS[i], \".png\"), this_plot)\n}\n\npng_files <- Sys.glob(\"images/CI_plot*.png\")\n\ngifski::gifski(\n  png_files,\n  \"CI_animation.gif\",    #output file name\n  height = 1600, width = 1600, #you may change the resolution\n  delay = 1/2                #seconds\n)\n```\n:::\n\n\n:::::\n\n::: {.callout-warning}\n## DCP3\n:::\n\n# Probability Perceptions\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n:::::: {style=\"font-size: 1.5em;\"}\nWe filled out a survey to judge the following terms on the scale from zero to 100 percent.\t\n::::::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n* certainly\n* frequently\n* likely\n* maybe\n* never\n* often\n* rarely\n* possibly\n* probably\n* unlikely\n:::\n\n::::\n\n::: {.callout-tip}\n## Pivot Tables\n\nThere are times when making a **pivot table** eases upcoming calculations. The resultant table may be arranged to be wider or longer.\n\n* long: more rows and fewer columns\n* wide: more columns and fewer rows\n:::\n\n## Three Words\n\n### subset\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n:::::: {style=\"font-size: 1.25em;\"}\nTo ease understanding of this concept, let us look at just a small subset of the data.\n::::::\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_wide <- prob_df |>\n  select(rarely, likely, frequently) |>\n  slice(1:5)\n```\n:::\n\n\n:::\n\n::::\n\n### wide\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dtgoukwyce\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dtgoukwyce table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dtgoukwyce thead, #dtgoukwyce tbody, #dtgoukwyce tfoot, #dtgoukwyce tr, #dtgoukwyce td, #dtgoukwyce th {\n  border-style: none;\n}\n\n#dtgoukwyce p {\n  margin: 0;\n  padding: 0;\n}\n\n#dtgoukwyce .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dtgoukwyce .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dtgoukwyce .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dtgoukwyce .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dtgoukwyce .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dtgoukwyce .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dtgoukwyce .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dtgoukwyce .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dtgoukwyce .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dtgoukwyce .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dtgoukwyce .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dtgoukwyce .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dtgoukwyce .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dtgoukwyce .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dtgoukwyce .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dtgoukwyce .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dtgoukwyce .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dtgoukwyce .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dtgoukwyce .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dtgoukwyce .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dtgoukwyce .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dtgoukwyce .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dtgoukwyce .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dtgoukwyce .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dtgoukwyce .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dtgoukwyce .gt_left {\n  text-align: left;\n}\n\n#dtgoukwyce .gt_center {\n  text-align: center;\n}\n\n#dtgoukwyce .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dtgoukwyce .gt_font_normal {\n  font-weight: normal;\n}\n\n#dtgoukwyce .gt_font_bold {\n  font-weight: bold;\n}\n\n#dtgoukwyce .gt_font_italic {\n  font-style: italic;\n}\n\n#dtgoukwyce .gt_super {\n  font-size: 65%;\n}\n\n#dtgoukwyce .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dtgoukwyce .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dtgoukwyce .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dtgoukwyce .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dtgoukwyce .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dtgoukwyce .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dtgoukwyce .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dtgoukwyce .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dtgoukwyce div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Probability Perceptions</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>wide table</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"rarely\">rarely</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"likely\">likely</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"frequently\">frequently</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">95</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">60</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">80</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">10</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">50</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">30</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">75</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">65</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">80</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"> SML 201</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### pivot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_tall <- prob_wide |>\n  pivot_longer(\n    cols = everything(),  #column selection\n    names_to = \"term\",    #categorical labels\n    values_to = \"percent\" #numerical values\n  )\n```\n:::\n\n\n### tall\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yybmttwefo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yybmttwefo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yybmttwefo thead, #yybmttwefo tbody, #yybmttwefo tfoot, #yybmttwefo tr, #yybmttwefo td, #yybmttwefo th {\n  border-style: none;\n}\n\n#yybmttwefo p {\n  margin: 0;\n  padding: 0;\n}\n\n#yybmttwefo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yybmttwefo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yybmttwefo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yybmttwefo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yybmttwefo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yybmttwefo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yybmttwefo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yybmttwefo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yybmttwefo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yybmttwefo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yybmttwefo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yybmttwefo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yybmttwefo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yybmttwefo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yybmttwefo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yybmttwefo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yybmttwefo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yybmttwefo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yybmttwefo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yybmttwefo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yybmttwefo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yybmttwefo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yybmttwefo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yybmttwefo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yybmttwefo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yybmttwefo .gt_left {\n  text-align: left;\n}\n\n#yybmttwefo .gt_center {\n  text-align: center;\n}\n\n#yybmttwefo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yybmttwefo .gt_font_normal {\n  font-weight: normal;\n}\n\n#yybmttwefo .gt_font_bold {\n  font-weight: bold;\n}\n\n#yybmttwefo .gt_font_italic {\n  font-style: italic;\n}\n\n#yybmttwefo .gt_super {\n  font-size: 65%;\n}\n\n#yybmttwefo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yybmttwefo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yybmttwefo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yybmttwefo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yybmttwefo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yybmttwefo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yybmttwefo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yybmttwefo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yybmttwefo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\" style>Probability Perceptions</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>tall table</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"percent\">percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">95</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">60</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">80</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">10</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">50</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">30</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">75</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">65</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">80</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"> SML 201</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### juxtaposed\n\n::::: {.panel-tabset}\n\n#### tables\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zpxoxnjztv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zpxoxnjztv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zpxoxnjztv thead, #zpxoxnjztv tbody, #zpxoxnjztv tfoot, #zpxoxnjztv tr, #zpxoxnjztv td, #zpxoxnjztv th {\n  border-style: none;\n}\n\n#zpxoxnjztv p {\n  margin: 0;\n  padding: 0;\n}\n\n#zpxoxnjztv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zpxoxnjztv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zpxoxnjztv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zpxoxnjztv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zpxoxnjztv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zpxoxnjztv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zpxoxnjztv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zpxoxnjztv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zpxoxnjztv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zpxoxnjztv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zpxoxnjztv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zpxoxnjztv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zpxoxnjztv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zpxoxnjztv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zpxoxnjztv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpxoxnjztv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zpxoxnjztv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zpxoxnjztv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zpxoxnjztv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpxoxnjztv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zpxoxnjztv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpxoxnjztv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zpxoxnjztv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpxoxnjztv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zpxoxnjztv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpxoxnjztv .gt_left {\n  text-align: left;\n}\n\n#zpxoxnjztv .gt_center {\n  text-align: center;\n}\n\n#zpxoxnjztv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zpxoxnjztv .gt_font_normal {\n  font-weight: normal;\n}\n\n#zpxoxnjztv .gt_font_bold {\n  font-weight: bold;\n}\n\n#zpxoxnjztv .gt_font_italic {\n  font-style: italic;\n}\n\n#zpxoxnjztv .gt_super {\n  font-size: 65%;\n}\n\n#zpxoxnjztv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zpxoxnjztv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zpxoxnjztv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zpxoxnjztv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zpxoxnjztv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zpxoxnjztv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zpxoxnjztv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zpxoxnjztv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zpxoxnjztv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Probability Perceptions</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>wide table</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"rarely\">rarely</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"likely\">likely</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"frequently\">frequently</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">95</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">60</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">80</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">10</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">50</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">30</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">75</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"rarely\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td>\n<td headers=\"likely\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">65</td>\n<td headers=\"frequently\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">80</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"> SML 201</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"eepsmrrljd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#eepsmrrljd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#eepsmrrljd thead, #eepsmrrljd tbody, #eepsmrrljd tfoot, #eepsmrrljd tr, #eepsmrrljd td, #eepsmrrljd th {\n  border-style: none;\n}\n\n#eepsmrrljd p {\n  margin: 0;\n  padding: 0;\n}\n\n#eepsmrrljd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#eepsmrrljd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#eepsmrrljd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#eepsmrrljd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#eepsmrrljd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#eepsmrrljd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#eepsmrrljd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#eepsmrrljd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#eepsmrrljd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#eepsmrrljd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#eepsmrrljd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eepsmrrljd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#eepsmrrljd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#eepsmrrljd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#eepsmrrljd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eepsmrrljd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#eepsmrrljd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#eepsmrrljd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#eepsmrrljd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eepsmrrljd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#eepsmrrljd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eepsmrrljd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#eepsmrrljd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eepsmrrljd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eepsmrrljd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eepsmrrljd .gt_left {\n  text-align: left;\n}\n\n#eepsmrrljd .gt_center {\n  text-align: center;\n}\n\n#eepsmrrljd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#eepsmrrljd .gt_font_normal {\n  font-weight: normal;\n}\n\n#eepsmrrljd .gt_font_bold {\n  font-weight: bold;\n}\n\n#eepsmrrljd .gt_font_italic {\n  font-style: italic;\n}\n\n#eepsmrrljd .gt_super {\n  font-size: 65%;\n}\n\n#eepsmrrljd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#eepsmrrljd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#eepsmrrljd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#eepsmrrljd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#eepsmrrljd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#eepsmrrljd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#eepsmrrljd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#eepsmrrljd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#eepsmrrljd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\" style>Probability Perceptions</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>tall table</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"percent\">percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">95</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">60</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">80</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">10</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">50</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">30</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">75</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">70</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">rarely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #FF6347;\">15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">likely</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #9B30FF;\">65</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">frequently</td>\n<td headers=\"percent\" class=\"gt_row gt_center\" style=\"background-color: #87CEFF;\">80</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"> SML 201</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n::::\n\n#### gt\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_wide |>\n  gt() |>\n  cols_align(align = \"center\") |>\n  tab_footnote(footnote = \"SML 201\") |>\n  tab_header(\n    title = \"Probability Perceptions\",\n    subtitle = \"wide table\"\n  ) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  tab_style(\n    style = cell_fill(color = \"tomato1\"),\n    locations = cells_body(columns = rarely)\n  ) |>\n  tab_style(\n    style = cell_fill(color = \"purple1\"),\n    locations = cells_body(columns = likely)\n  ) |>\n  tab_style(\n    style = cell_fill(color = \"skyblue1\"),\n    locations = cells_body(columns = frequently)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_tall |>\n  gt() |>\n  cols_align(align = \"center\") |>\n  tab_footnote(footnote = \"SML 201\") |>\n  tab_header(\n    title = \"Probability Perceptions\",\n    subtitle = \"tall table\"\n  ) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  tab_style(\n    style = cell_fill(color = \"tomato1\"),\n    locations = cells_body(rows = term == \"rarely\")\n  ) |>\n  tab_style(\n    style = cell_fill(color = \"purple1\"),\n    locations = cells_body(rows = term == \"likely\")\n  ) |>\n  tab_style(\n    style = cell_fill(color = \"skyblue1\"),\n    locations = cells_body(rows = term == \"frequently\")\n  )\n```\n:::\n\n\n:::::\n\n### plotting\n\n::::: {.panel-tabset}\n\n#### density\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n#### code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_tall |>\n  ggplot() +\n  geom_density(aes(x = percent, fill = term),\n               alpha = 0.201) +\n  labs(title = \"Probability Perceptions\",\n       subtitle = \"density plot\",\n       caption = \"SML 201\") +\n  scale_fill_manual(values = c(\"skyblue1\", \"purple1\", \"tomato1\")) +\n  theme_minimal()\n```\n:::\n\n\n:::::\n\n### reversion\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_wide <- prob_tall |>\n  mutate(id = rep(1:5, each = 3)) |>\n  pivot_wider(id_cols = id,\n              names_from = term,\n              values_from = percent)\n```\n:::\n\n\n\n## Nine Words\n\n::::: {.panel-tabset}\n\n### ranking\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   term         q25 median   q75\n   <chr>      <dbl>  <dbl> <dbl>\n 1 never          0      0   0  \n 2 rarely        10     20  24.5\n 3 unlikely      10     20  25  \n 4 possibly      30     40  50  \n 5 maybe         50     50  50  \n 6 likely        60     70  75  \n 7 often         60     70  80  \n 8 probably      65     70  80  \n 9 frequently    70     75  80  \n10 certainly    100    100 100  \n```\n\n\n:::\n:::\n\n\n### boxplots\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_confidence_intervals_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n### codes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_long <- prob_df |>\n  pivot_longer(cols = everything(),\n    names_to = \"term\", \n    values_to = \"percent\")\n\nprob_long |> \n  group_by(term) |> \n  summarize(q25 = quantile(percent, 0.25, na.rm = TRUE),\n            median = median(percent, na.rm = TRUE),\n            q75 = quantile(percent, 0.75, na.rm = TRUE)) |>\n  arrange(median, q25, q75)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_long |>\n  group_by(term) |>\n  mutate(median = median(percent, na.rm = TRUE)) |>\n  ungroup() |>\n  ggplot() +\n  geom_boxplot(aes(x = percent, \n                   y = fct_reorder(term, median),\n                   color = term)) +\n  labs(title = \"Perceptions of Probability\",\n       subtitle = \"Spring 2026 Semester\",\n       caption = \"SML 201\",\n       x = \"percent\", y = \"\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n:::\n\n\n:::::\n\n\n\n\n\n\n\n# Quo Vadimus?\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n* Due Friday (March 27)\n  * Precept 7\n  * Read Chapter 9 (quiz)\n\n* Project 2 (due April 7)\n* Exam 2 (April 23)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n![BOOlean logic](BOOlean_logic.png)\n\n:::\n\n::::\n\n\n# Footnotes\n\n::: {.callout-note collapse=\"true\"}\n## (optional) Additional Resources\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.4  forcats_1.0.0    stringr_1.5.1    dplyr_1.1.4     \n [5] purrr_1.1.0      readr_2.1.5      tidyr_1.3.1      tibble_3.3.0    \n [9] tidyverse_2.0.0  janitor_2.2.1    infer_1.0.9      gt_1.0.0        \n[13] ggtext_0.1.2     ggimage_0.3.5    ggplot2_4.0.0    bayesrules_0.0.2\n\nloaded via a namespace (and not attached):\n  [1] RColorBrewer_1.1-3      tensorA_0.36.2.1        rstudioapi_0.17.1      \n  [4] jsonlite_2.0.0          magrittr_2.0.3          magick_2.8.7           \n  [7] farver_2.1.2            nloptr_2.2.1            rmarkdown_2.29         \n [10] fs_1.6.6                vctrs_0.6.5             minqa_1.2.8            \n [13] base64enc_0.1-3         htmltools_0.5.8.1       distributional_0.5.0   \n [16] curl_6.4.0              gridGraphics_0.5-1      sass_0.4.10            \n [19] StanHeaders_2.32.10     htmlwidgets_1.6.4       plyr_1.8.9             \n [22] zoo_1.8-14              commonmark_2.0.0        igraph_2.1.4           \n [25] mime_0.13               lifecycle_1.0.4         pkgconfig_2.0.3        \n [28] colourpicker_1.3.0      Matrix_1.7-4            R6_2.6.1               \n [31] fastmap_1.2.0           rbibutils_2.3           shiny_1.11.1           \n [34] snakecase_0.11.1        digest_0.6.37           crosstalk_1.2.2        \n [37] labeling_0.4.3          timechange_0.3.0        abind_1.4-8            \n [40] compiler_4.5.2          proxy_0.4-27            bit64_4.6.0-1          \n [43] fontquiver_0.2.1        withr_3.0.2             S7_0.2.0               \n [46] backports_1.5.0         inline_0.3.21           shinystan_2.6.0        \n [49] QuickJSR_1.8.0          pkgbuild_1.4.8          MASS_7.3-65            \n [52] rappdirs_0.3.3          gtools_3.9.5            loo_2.8.0              \n [55] tools_4.5.2             httpuv_1.6.16           threejs_0.3.4          \n [58] glue_1.8.0              nlme_3.1-168            promises_1.3.3         \n [61] gridtext_0.1.5          grid_4.5.2              checkmate_2.3.2        \n [64] reshape2_1.4.4          generics_0.1.4          gtable_0.3.6           \n [67] tzdb_0.5.0              class_7.3-23            hms_1.1.3              \n [70] utf8_1.2.6              xml2_1.3.8              pillar_1.11.0          \n [73] markdown_2.0            vroom_1.6.5             yulab.utils_0.2.4      \n [76] posterior_1.6.1         later_1.4.2             splines_4.5.2          \n [79] lattice_0.22-7          bit_4.6.0               survival_3.8-3         \n [82] tidyselect_1.2.1        fontLiberation_0.1.0    miniUI_0.1.2           \n [85] knitr_1.50              fontBitstreamVera_0.1.1 reformulas_0.4.1       \n [88] gridExtra_2.3           litedown_0.7            V8_6.0.5               \n [91] groupdata2_2.0.5        stats4_4.5.2            xfun_0.52              \n [94] rstanarm_2.32.1         matrixStats_1.5.0       DT_0.34.0              \n [97] rstan_2.32.7            stringi_1.8.7           ggfun_0.2.0            \n[100] yaml_2.3.10             boot_1.3-32             evaluate_1.0.4         \n[103] codetools_0.2-20        gdtools_0.5.0           ggplotify_0.1.3        \n[106] cli_3.6.5               RcppParallel_5.1.10     shinythemes_1.2.0      \n[109] xtable_1.8-4            systemfonts_1.3.2       Rdpack_2.6.4           \n[112] Rcpp_1.1.0              parallel_4.5.2          rstantools_2.4.0       \n[115] dygraphs_1.1.1.6        bayesplot_1.14.0        lme4_1.1-37            \n[118] ggiraph_0.9.6           scales_1.4.0            xts_0.14.1             \n[121] e1071_1.7-16            crayon_1.5.3            rlang_1.1.6            \n[124] shinyjs_2.1.0          \n```\n\n\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n::::: {.panel-tabset}\n\n\n\n:::::",
    "supporting": [
      "14_confidence_intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}