{
  "hash": "6c6726d9a157d9c7ed2a23f8779806a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8: Multiple Linear Regression\"\nauthor: \"Derek Sollberger\"\ndate: \"2024-10-01\"\nformat:\n  html:\n    toc: true\n    theme: cerulean\n    # theme: customstyle.scss\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"corrplot\")  #visualize correlations simultaneously\nlibrary(\"gt\")        #great tables\nlibrary(\"tidyverse\") #tools for data wrangling and visualization\n\noakland_green <- \"#003831\"\noakland_yellow <- \"#EFB21E\"\n\n# user-defined function\ncor2text <- function(x,y, num_digits = 4){\n  # This function will compute a correlation, round the result, and describe the results\n  # INPUTS:\n  ## x: numerical vector\n  ## y: numerical vector\n  ## num_digits: number of digits for rounding (default: 4)\n  # OUTPUT: string\n  \n  r = cor(x,y, use = \"pairwise.complete.obs\")\n  \n  cor_des <- case_when(\n    r >= 0.7 ~ \"strongly and positively correlated\",\n    r >= 0.4 & r < 0.7 ~ \"slightly and positively correlated\",\n    r <= -0.4 & r > -0.7 ~ \"slightly and negatively correlated\",\n    r <= -0.7 ~ \"strongly and negatively correlated\",\n    .default = \"virtually uncorrelated\"\n  )\n  \n  #return\n  paste0(\"r = \", round(r, num_digits),\n         \", \", cor_des)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_df <- readr::read_csv(\"https://raw.githubusercontent.com/dsollberger/sml201slides/main/data/baseball_data_90s.csv\")\n\noffense_cats <- c(\"R\", \"H\", \"X2B\", \"X3B\", \"HR\", \"BB\", \"SO\", \"SB\")\ndefense_cats <- c(\"RA\", \"ER\", \"HA\", \"HRA\", \"BBA\", \"SOA\", \"E\", \"FP\")\n```\n:::\n\n\n\n\n# SML 201\n\n## Start\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* **Goal**: Expand to larger regression models\n\n* **Objective**: Include multiple linear terms and an interaction term\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n![Moneyball (2011)](moneyball_movie.png)\n\n:::\n\n::::\n\n## Story\n\n:::: {.panel-tabset}\n\n### Book\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n![Moneyball (2003)](moneyball_book.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"60%\"}\n* <span style = \"color:#003831\">**Oakland Athletics**</span> fielded a competitive team despite having a payroll size around 1/3 of some other franchises\n* Traditional scouting vs modern statistics\n* **Idea**: Can we identify qualities (variables) in baseball players that lead to more wins?\n:::\n\n::::\n\n### Finance\n\n![MLB Team Salaries, 2002](MONEYBALLchart.png)\n\n* image source: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:MONEYBALLchart.png)\n\n::::\n\n\n\n\n\n## Data\n\n:::: {.panel-tabset}\n\n### Lahman\n\nToday’s data set comes from the `Lahman` package, which contains a lot of historical data about Major League Baseball.\n\n* [Lahman package CRAN page](https://cran.r-project.org/web/packages/Lahman/index.html)\n\n### Offense\n\n* `R`: runs\n* `H`: hits\n* `X2B`: doubles\n* `X3B`: triples\n* `HR`: home runs\n* `BB`: walks\n* `SO`: strikeouts (by hitters)\n* `SB`: stolen bases\n\n### Defense\n\n* `RA`: runs allowed\n* `ER`: earned runs\n* `HA`: hits allowed\n* `HRA`: home runs allowed\n* `BBA`: walks allowed\n* `SOA`: strikeouts (by pitchers)\n* `E`: errors\n* `FP`: fielding percentage\n\n::::\n\n\n# Searching for Wins\n\n## Correlation\n\n:::: {.panel-tabset}\n\n### Offense\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_multiple_linear_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_df |>\n  ggplot(aes(x = R, y = W)) +\n  geom_point(color = oakland_green) + \n  labs(title = \"Wins vs Runs Scored\",\n       subtitle = paste0(\"r = \", round(cor_value, 4), \n                         \", slightly and positively correlated\"),\n       caption = \"seasons 1990 to 1999\",\n       x = \"runs scored\",\n       y = \"wins\") +\n  theme_minimal()\n```\n:::\n\n\n\n### Defense\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_multiple_linear_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_value <- cor(bb_df$RA, bb_df$W)\n\nbb_df |>\n  ggplot(aes(x = RA, y = W)) +\n  geom_point(color = oakland_green) + \n  labs(title = \"Wins vs Runs Allowed\",\n       subtitle = paste0(\"r = \", round(cor_value, 4), \n                         \", virtually uncorrelated\"),\n       caption = \"seasons 1990 to 1999\",\n       x = \"runs allowed\",\n       y = \"wins\") +\n  theme_minimal()\n```\n:::\n\n\n\n::::\n\n\n## Correlation Matrices\n\n:::: {.panel-tabset}\n\n### Offense\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_multiple_linear_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_df |>\n  select(any_of(offense_cats)) |>\n  cor() |>\n  corrplot.mixed(order = \"FPC\",\n                 upper = \"ellipse\")\n```\n:::\n\n\n\n### Defense\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_multiple_linear_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_df |>\n  select(any_of(defense_cats)) |>\n  cor() |>\n  corrplot.mixed(order = \"FPC\",\n                 upper = \"ellipse\")\n```\n:::\n\n\n\n::::\n\n::: {.callout-note collapse=\"true\"}\n## New Directions\n\nSo far, a sabermetrician might observe and ask\n\n* Wins are correlated with runs scored\n* What correlates well with runs scored?\n\n:::\n\n\n# Linear Regression\n\n:::: {.panel-tabset}\n\n### Decreasing\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_multiple_linear_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n### 2\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = HR ~ X3B, data = bb_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-75.904 -26.951  -4.516  23.685 106.423 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 176.3250     8.3418  21.138  < 2e-16 ***\nX3B          -0.8879     0.2582  -3.439 0.000674 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 38.16 on 276 degrees of freedom\nMultiple R-squared:  0.04109,\tAdjusted R-squared:  0.03762 \nF-statistic: 11.83 on 1 and 276 DF,  p-value: 0.0006737\n```\n\n\n:::\n:::\n\n\n\n### 3\n\n* negative correlation $\\Longleftrightarrow$ decreasing trend\n* $R^{2} \\approx 0.04$: bad model\n\n### code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(HR ~ X3B, data = bb_df))\n\nbb_df |>\n  ggplot(aes(x = X3B, y = HR)) +\n  geom_point(color = oakland_yellow) + \n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              color = \"red\") +\n  labs(title = \"Home Runs vs Triples\",\n       subtitle = cor2text(bb_df$RA, bb_df$W),\n       caption = \"seasons 1990 to 1999\",\n       x = \"triples\",\n       y = \"home runs\") +\n  theme_minimal()\n```\n:::\n\n\n\n### Increasing\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_multiple_linear_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n### 5\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = R ~ H, data = bb_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-140.864  -40.845   -1.513   44.465  153.202 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -108.79033   33.84845  -3.214  0.00146 ** \nH              0.59342    0.02392  24.811  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 58.25 on 276 degrees of freedom\nMultiple R-squared:  0.6904,\tAdjusted R-squared:  0.6893 \nF-statistic: 615.6 on 1 and 276 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n### 6\n\n* positive correlation $\\Longleftrightarrow$ increasing trend\n* $R^{2} \\approx 0.6893$: good model\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(R ~ H, data = bb_df))\n\nbb_df |>\n  ggplot(aes(x = H, y = R)) +\n  geom_point(color = oakland_green) + \n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              color = \"blue\") +\n  labs(title = \"Runs Scored vs Hits\",\n       subtitle = cor2text(bb_df$R, bb_df$H),\n       caption = \"seasons 1990 to 1999\",\n       x = \"hits\",\n       y = \"runs scored\") +\n  theme_minimal()\n```\n:::\n\n\n\n::::\n\n## Model Equation\n\n:::: {.panel-tabset}\n\n### Math\n\n$$\\text{Runs} = \\beta_{0} + \\beta_{1}(\\text{Hits})$$\n\n* $\\beta_{0}$: intercept\n* $\\beta_{1}$: change in Runs with respect to Hits\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(R ~ H, data = bb_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = R ~ H, data = bb_df)\n\nCoefficients:\n(Intercept)            H  \n  -108.7903       0.5934  \n```\n\n\n:::\n:::\n\n\n\n* $\\beta_{0} \\approx -108.7903$\n* $\\beta_{1} \\approx 0.5934$\n\n$$\\text{Runs} = -108.7903 + 0.5934(\\text{Hits})$$\n\n### Intercept\n\nIn a hypothetical scenario where a team has zero hits,\n\n$$\\text{Runs} = -108.7903 + 0.5934(0)$$\nthe model estimates that the baseball team will win about negative 109 games in a season.\n\n* see note about \"Removing the intercept\" below\n\n### Slope\n\nWe continue to intercept the rate of change (or slope) \n\n$$\\beta_{1} \\approx 0.5934$$\n\nwith language like\n\n> For every additional hit, the number of runs increases by about 0.5934.\n\n### Determination\n\nWe can get a sense of how useful this model can be with the coefficient of determination.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(R ~ H, data = bb_df) #baseline model\nsummary(mod1)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6893222\n```\n\n\n:::\n:::\n\n\n\n> According to the coefficient of determination, this model (with \"Hits\" as an explanatory variable) explains about 69 percent of the variance in runs scored.\n\n::::\n\n::: {.callout-caution collapse=\"true\"}\n## Removing the Intercept\n\nSometimes an analyst might want to remove the intercept term (here: zero hits should imply zero runs?)\n\n$$\\text{Runs} = \\beta_{1}(\\text{Hits})$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod0 <- lm(R ~ H - 1, data = bb_df) #removed intercept\nmod0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = R ~ H - 1, data = bb_df)\n\nCoefficients:\n    H  \n0.517  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod0)$adj.r.squared #removed intercept\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.993489\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)$adj.r.squared #baseline model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6893222\n```\n\n\n:::\n:::\n\n\n\nWhile removing the intercept seems great in this simple example, in practice removing the intercept does not tend to generalize to larger models or inclusion of additional data.\n\n:::\n\n\n# Multiple Linear Regression\n\nWe can include more explanatory variables in our models\n\n:::: {.panel-tabset}\n\n### Math\n\n$$\\text{Runs} = \\beta_{0} + \\beta_{1}(\\text{Hits}) + \\beta_{2}(\\text{Walks})$$\n\n* $\\beta_{0}$: intercept\n* $\\beta_{1}$: change in Runs with respect to Hits\n* $\\beta_{2}$: change in Runs with respect to Walks\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(R ~ H + BB, data = bb_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = R ~ H + BB, data = bb_df)\n\nCoefficients:\n(Intercept)            H           BB  \n  -124.4358       0.4382       0.4395  \n```\n\n\n:::\n:::\n\n\n\n### Intercept\n\nIn a hypothetical scenario where a team has zero hits and zero walks,\n\n$$\\text{Runs} = -124.4358 + 0.4382(0) + 0.4395(0)$$\nthe model estimates that the baseball team will win about negative 124 games in a season.\n\n### Slopes\n\nIn regression, we say that we *control* for other variables by treating other variables as constants.\n\n$$\\text{Runs} = -124.4358 + 0.4382(\\text{Hits}) + 0.4395(\\text{Walks})$$\n\n> Holding walks constant, for every additional hit, the number of runs increases by about 0.4382.\n\n> Holding hits constant, for every additional walk, the number of runs increases by about 0.4395.\n\n### Determination\n\nContinuing our usage of the coefficient of determination\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lm(R ~ H + BB, data = bb_df) \n\nsummary(mod1)$adj.r.squared #baseline model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6893222\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod2)$adj.r.squared #slightly modified model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7735558\n```\n\n\n:::\n:::\n\n\n\n> According to the coefficient of determination, this model (with 2 explanatory variables) explains about 77 percent of the variance in runs scored.\n\n::::\n\n## Different Models, Different Coefficients\n\n::: {.callout-warning collapse=\"true\"}\n## Coefficients are different in different models\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gnrtypbdmk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gnrtypbdmk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gnrtypbdmk thead, #gnrtypbdmk tbody, #gnrtypbdmk tfoot, #gnrtypbdmk tr, #gnrtypbdmk td, #gnrtypbdmk th {\n  border-style: none;\n}\n\n#gnrtypbdmk p {\n  margin: 0;\n  padding: 0;\n}\n\n#gnrtypbdmk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gnrtypbdmk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gnrtypbdmk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gnrtypbdmk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gnrtypbdmk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gnrtypbdmk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gnrtypbdmk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gnrtypbdmk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gnrtypbdmk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gnrtypbdmk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gnrtypbdmk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gnrtypbdmk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gnrtypbdmk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gnrtypbdmk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gnrtypbdmk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gnrtypbdmk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gnrtypbdmk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gnrtypbdmk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gnrtypbdmk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gnrtypbdmk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gnrtypbdmk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gnrtypbdmk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gnrtypbdmk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gnrtypbdmk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gnrtypbdmk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gnrtypbdmk .gt_left {\n  text-align: left;\n}\n\n#gnrtypbdmk .gt_center {\n  text-align: center;\n}\n\n#gnrtypbdmk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gnrtypbdmk .gt_font_normal {\n  font-weight: normal;\n}\n\n#gnrtypbdmk .gt_font_bold {\n  font-weight: bold;\n}\n\n#gnrtypbdmk .gt_font_italic {\n  font-style: italic;\n}\n\n#gnrtypbdmk .gt_super {\n  font-size: 65%;\n}\n\n#gnrtypbdmk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gnrtypbdmk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gnrtypbdmk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gnrtypbdmk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gnrtypbdmk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gnrtypbdmk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gnrtypbdmk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gnrtypbdmk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gnrtypbdmk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Early Baseball Stats Models</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Comparing the coefficients</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"coefs\">coefs</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"mod1\">mod1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"mod2\">mod2</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"coefs\" class=\"gt_row gt_center\">beta_0</td>\n<td headers=\"mod1\" class=\"gt_row gt_center\" style=\"background-color: #003831; color: #EFB21E;\">-108.7903</td>\n<td headers=\"mod2\" class=\"gt_row gt_center\" style=\"background-color: #EFB21E; color: #003831;\">-124.4358</td></tr>\n    <tr><td headers=\"coefs\" class=\"gt_row gt_center\">beta_1</td>\n<td headers=\"mod1\" class=\"gt_row gt_center\" style=\"background-color: #003831; color: #EFB21E;\">0.5934</td>\n<td headers=\"mod2\" class=\"gt_row gt_center\" style=\"background-color: #EFB21E; color: #003831;\">0.4382</td></tr>\n    <tr><td headers=\"coefs\" class=\"gt_row gt_center\">beta_2</td>\n<td headers=\"mod1\" class=\"gt_row gt_center\" style=\"background-color: #003831; color: #EFB21E;\">-</td>\n<td headers=\"mod2\" class=\"gt_row gt_center\" style=\"background-color: #EFB21E; color: #003831;\">0.4395</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"> SML 201</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_stats_df <- data.frame(\n  coefs = c(\"beta_0\", \"beta_1\", \"beta_2\"),\n  mod1 = c(-108.7903, 0.5934, \"-\"),\n  mod2 = c(-124.4358, 0.4382, 0.4395)\n)\n\nmod_stats_df |>\n  gt() |>\n  cols_align(align = \"center\") |>\n  tab_footnote(footnote = \"SML 201\") |>\n  tab_header(\n    title = \"Early Baseball Stats Models\",\n    subtitle = \"Comparing the coefficients\"\n  ) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  tab_style(\n    style = list(\n      cell_fill(color = oakland_green),\n      cell_text(color = oakland_yellow)\n    ),\n    locations = cells_body(columns = mod1)\n  ) |>\n  tab_style(\n    style = list(\n      cell_fill(color = oakland_yellow),\n      cell_text(color = oakland_green)\n    ),\n    locations = cells_body(columns = mod2)\n  )\n```\n:::\n\n\n\n:::\n\nIn practice, we tend to explore several models through trial-and-error.  After choosing a model, we then scrutinize the interpretation of the $\\beta$ coefficients.\n\n\n# Interlude: Sabermetrics\n\n:::: {.panel-tabset}\n\n### Chadwick\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n![Henry Chadwick](Henry_Chadwick_pic.png)\n:::\n\n::: {.column width=\"5%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n* Henry Chadwick\n* writer, historian\n* 1824 to 1908\n* \"Father of Baseball\"\n* invented the box score (how games are summarized in newspapers)\n* refined definitions of concepts like errors and batting average\n:::\n\n::: {.column width=\"5%\"}\n\n:::\n\n::: {.column width=\"20%\"}\n![refined discussion of early baseball statistics](Henry_Chadwick_book.png)\n:::\n\n::::\n\n### Sabermetrics\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n![Bill James](Bill_James_pic.png)\n:::\n\n::: {.column width=\"5%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\nWe tend to call the statistical analysis of baseball **sabermetrics**.  Bill James coined the term in 1980, and described it as \"the search for objective knowledge about baseball\" ([source](https://www.britannica.com/sports/sabermetrics/The-rise-of-advanced-statistics))\n\n* SABR: Society for American Baseball Research\n:::\n\n::: {.column width=\"5%\"}\n\n:::\n\n::: {.column width=\"20%\"}\n![refined discussion of modern baseball statistics](Bill_James_book.png)\n:::\n\n::::\n\n### Moneyball\n\n![Moneyball meme](Moneyball_meme.png)\n\n### Derived\n\nOver time, baseball writers wanted to talk about batters (offense) in more ways.  From the previous measured variables, here are some of the *derived variables* that became common in baseball discussions.\n\n$$BA = \\frac{H}{AB}$$\n$$OBP = \\frac{H + BB + HBP}{AB}$$\n$$SLG = \\frac{H + 2B + 2*3B + 3*HR}{AB}$$\n$$OPS = OBP + SLG$$\n\n::::\n\n\n# Model Selection\n\n## Augmentation\n\nWe can attach new columns and calculations using `mutate`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_df <- bb_df |>\n  mutate(BA = H/AB,               #batting average\n         OBP = (H + BB + HBP)/AB, #on-base percentage\n         SLG = (H + X2B + 2*X3B + 3*HR)/AB, #slugging percentage\n         OPS = OBP + SLG)         #on-base plus slugging\n```\n:::\n\n\n\n* Stats like runs, hits, walks, and strikeouts are called **count statistics**.  Baseball players tend to accumulate count statistics with more playing time.\n* Stats like `BA`, `OBP`, and `SLG`are called **rate statistics**.  These baseball statistics are adjusted over playing time.\n* These derived statistics may be better to evaluate *individual* baseball players (rather than whole teams).\n* Aside: yes, it may be silly to add together `OBP` and `SLG` (i.e. two rate statistics), but baseball writers really like this calculation.\n\n## Using the Derived Statistics\n\nWe build a model for different allocations of explanatory variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_BA  <- lm(R ~ BA,  data = bb_df)\nfit_OBP <- lm(R ~ OBP, data = bb_df)\nfit_SLG <- lm(R ~ SLG, data = bb_df)\nfit_OPS <- lm(R ~ OBP + SLG, data = bb_df)\n```\n:::\n\n\n\n## Measuring the Models\n\nWe use the coefficients of determination to help us rank the models.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_BA)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3445441\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_OBP)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4279833\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_SLG)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.433078\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_OPS)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4902423\n```\n\n\n:::\n:::\n\n\n\n\n## Picking the Best Model\n\n:::: {.panel-tabset}\n\n### gt\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nfsogudjjk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nfsogudjjk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nfsogudjjk thead, #nfsogudjjk tbody, #nfsogudjjk tfoot, #nfsogudjjk tr, #nfsogudjjk td, #nfsogudjjk th {\n  border-style: none;\n}\n\n#nfsogudjjk p {\n  margin: 0;\n  padding: 0;\n}\n\n#nfsogudjjk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nfsogudjjk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nfsogudjjk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nfsogudjjk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nfsogudjjk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nfsogudjjk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nfsogudjjk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nfsogudjjk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nfsogudjjk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nfsogudjjk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nfsogudjjk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nfsogudjjk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nfsogudjjk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nfsogudjjk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nfsogudjjk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nfsogudjjk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nfsogudjjk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nfsogudjjk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nfsogudjjk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nfsogudjjk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nfsogudjjk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nfsogudjjk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nfsogudjjk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nfsogudjjk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nfsogudjjk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nfsogudjjk .gt_left {\n  text-align: left;\n}\n\n#nfsogudjjk .gt_center {\n  text-align: center;\n}\n\n#nfsogudjjk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nfsogudjjk .gt_font_normal {\n  font-weight: normal;\n}\n\n#nfsogudjjk .gt_font_bold {\n  font-weight: bold;\n}\n\n#nfsogudjjk .gt_font_italic {\n  font-style: italic;\n}\n\n#nfsogudjjk .gt_super {\n  font-size: 65%;\n}\n\n#nfsogudjjk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nfsogudjjk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nfsogudjjk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nfsogudjjk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nfsogudjjk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nfsogudjjk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nfsogudjjk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nfsogudjjk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nfsogudjjk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\" style>Derived Baseball Stats Models</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Comparing the coefficients of determination</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"models\">models</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"r2_vals\">r2_vals</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"models\" class=\"gt_row gt_center\">fit_BA</td>\n<td headers=\"r2_vals\" class=\"gt_row gt_center\">0.3445</td></tr>\n    <tr><td headers=\"models\" class=\"gt_row gt_center\">fit_OBP</td>\n<td headers=\"r2_vals\" class=\"gt_row gt_center\">0.4280</td></tr>\n    <tr><td headers=\"models\" class=\"gt_row gt_center\">fit_SLG</td>\n<td headers=\"r2_vals\" class=\"gt_row gt_center\">0.4331</td></tr>\n    <tr><td headers=\"models\" class=\"gt_row gt_center\" style=\"background-color: #EFB21E; color: #003831; font-weight: bold;\">fit_OPS</td>\n<td headers=\"r2_vals\" class=\"gt_row gt_center\" style=\"background-color: #EFB21E; color: #003831; font-weight: bold;\">0.4902</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"> SML 201</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_stats_df2 <- data.frame(\n  models = paste0(\"fit_\", c(\"BA\", \"OBP\", \"SLG\", \"OPS\")),\n  r2_vals = round(c(summary(fit_BA)$adj.r.squared,\n                    summary(fit_OBP)$adj.r.squared,\n                    summary(fit_SLG)$adj.r.squared,\n                    summary(fit_OPS)$adj.r.squared), 4)\n)\n\nmod_stats_df2 |>\n  gt() |>\n  cols_align(align = \"center\") |>\n  tab_footnote(footnote = \"SML 201\") |>\n  tab_header(\n    title = \"Derived Baseball Stats Models\",\n    subtitle = \"Comparing the coefficients of determination\"\n  ) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  tab_style(\n    style = list(\n      cell_fill(color = oakland_yellow),\n      cell_text(color = oakland_green,\n                weight = \"bold\")\n    ),\n    locations = cells_body(columns = c(models, r2_vals),\n                           rows = r2_vals == max(r2_vals))\n    # finds maximum value programmatically\n  )\n```\n:::\n\n\n\n::::\n\n\n\n\n# Interaction Terms\n\n## Before Interaction\n\nFirst, let us try another multiple linear regression model\n\n:::: {.panel-tabset}\n\n### Variables\n\n$$\\text{Wins} = \\beta_{0} + \\beta_{1}(\\text{Runs Scored}) + \\beta_{2}(\\text{Runs Allowed})$$\n\n* response variable: Wins\n* explanatory variables:\n\n    * Runs Scored (offense)\n    * Runs Allowed (defense)\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(W ~ R + RA, data = bb_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = W ~ R + RA, data = bb_df)\n\nCoefficients:\n(Intercept)            R           RA  \n   42.50059      0.12530     -0.07692  \n```\n\n\n:::\n:::\n\n\n\n### Intercept\n\nIn a hypothetical scenario where a team has zero runs and zero runs allowed,\n\n$$\\text{Wins} = 42.5006 + 0.1253(0) - 0.0769(0)$$\n\nthe model estimates that the baseball team will win about 43 games in a season.\n\n### Slopes\n\nIn regression, we say that we *control* for other variables by treating other variables as constants.\n\n$$\\text{Wins} = 42.5006 + 0.1253(\\text{Runs Scored}) - 0.0769(\\text{Runs Allowed})$$\n\n* Holding runs allowed constant, for every additional run *scored*, the number of wins *increases* by about 0.1253.\n\n* Holding runs scored constant, for every additional run *allowed*, the number of wins *decreases* by about 0.0769.\n\n### Determination\n\nWith our usage of the coefficient of determination\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithout_interaction <- lm(W ~ R + RA, data = bb_df)\n\nsummary(without_interaction)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.700125\n```\n\n\n:::\n:::\n\n\n\n> According to the coefficient of determination, this model (with 2 explanatory variables) explains about 70 percent of the variance in wins.\n\n::::\n\n## With an Interaction Term\n\nNow let us explore an interaction term\n\n:::: {.panel-tabset}\n\n### Variables\n\n$$\\begin{array}{rcl}\n\\text{Wins} & = & \\beta_{0} \\\\\n& & + \\beta_{1}(\\text{Runs Scored}) \\\\\n& & + \\beta_{2}(\\text{Runs Allowed}) \\\\\n& & + \\beta_{3}(\\text{Runs Scored})(\\text{Runs Allowed}) \\\\\n\\end{array}$$\n\n* response variable: Wins\n* explanatory variables:\n\n    * Runs Scored\n    * Runs Allowed\n    * interaction bteween Runs Scored and Runs Allowed\n    \n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(W ~ R + RA + R:RA, data = bb_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = W ~ R + RA + R:RA, data = bb_df)\n\nCoefficients:\n(Intercept)            R           RA         R:RA  \n -8.896e+01    3.082e-01    1.090e-01   -2.555e-04  \n```\n\n\n:::\n:::\n\n\n\n### Intercept\n\nIn a hypothetical scenario where a team has zero runs and zero runs allowed,\n\n$$\\text{Wins} = -88.96 + 0.3082(0) + 0.1090(0) - 0.0002(0)(0)$$\n\nthe model estimates that the baseball team will win about -89 games in a season.\n\n### Slopes\n\nTo get a sense of how many runs a MLB team allows in a season, we can use the `summary` command.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bb_df$RA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  448.0   655.2   721.0   726.5   794.0  1103.0 \n```\n\n\n:::\n:::\n\n\n\n#### Strong Defense\n\nSuppose that a MLB team has good defensive skills and allows about 650 runs in a season (i.e. around the 20th percentile).\n\n$$\\begin{array}{rcl} \n\\text{Wins} & = & -88.96 + 0.3082(\\text{Runs Scored}) + 0.1090(\\text{Runs Allowed}) - 0.0002(\\text{Runs Scored})(\\text{Runs Allowed}) \\\\\n ~ & = & -88.96 + 0.3082(\\text{Runs Scored}) + 0.1090(650) - 0.0002(\\text{Runs Scored})(650) \\\\\n  ~ & = & -18.11 + 0.1782(\\text{Runs Scored})\\\\\n\\end{array}$$\n\n> Holding runs allowed constant at 650, for every additional run scored, the number of wins increases by about 0.1782.\n\n#### Weak Defense\n\nSuppose that a MLB team has weak defensive skills and allows about 800 runs in a season (i.e. around the 80th percentile).\n\n$$\\begin{array}{rcl} \n\\text{Wins} & = & -88.96 + 0.3082(\\text{Runs Scored}) + 0.1090(\\text{Runs Allowed}) - 0.0002(\\text{Runs Scored})(\\text{Runs Allowed}) \\\\\n ~ & = & -88.96 + 0.3082(\\text{Runs Scored}) + 0.1090(800) - 0.0002(\\text{Runs Scored})(800) \\\\\n  ~ & = & -1.76 + 0.1482(\\text{Runs Scored})\\\\\n\\end{array}$$\n\n> Holding runs allowed constant at 800, for every additional run scored, the number of wins increases by about 0.1482.\n\n### Determination\n\nWith our usage of the coefficient of determination\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith_interaction <- lm(W ~ R + RA + R:RA, data = bb_df)\n\nsummary(without_interaction)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.700125\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(with_interaction)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.764043\n```\n\n\n:::\n:::\n\n\n\n> According to the coefficient of determination, this model (with the interaction term) explains about 76 percent of the variance in wins.\n\n::::\n\n# Epilogue: Picking Players\n\n:::: {.panel-tabset}\n\n### Bradford\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n![Chad Bradford](Chad_Bradford.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\"Billy, this is Chad Bradford. He's a relief pitcher. He is one of the most undervalued players in baseball. His defect is that he throws funny. Nobody in the big leagues cares about him, because he looks funny. This guy could be not just the best pitcher in our bullpen, but one of the most effective relief pitchers in all of baseball. This guy should cost $3 million a year. We can get him for $237,000.\" --- Peter Brand\n:::\n\n::::\n\n### Hatteberg\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n![Scott Hatteberg](Scott_Hatteberg.png)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n* <span style = \"color:#003831\">**Billy Beane**</span>: You don't know how to play 1st base. Scott...\n* <span style = \"color:#003831\">**Scott Hatteberg**</span>: That's right.\n* <span style = \"color:#003831\">**Billy Beane**</span>: It's not that hard, Scott. Tell him Wash.\n* <span style = \"color:#003831\">**Ron Washington**</span>: It's incredibly hard.\n* <span style = \"color:#003831\">**Billy Beane**</span>: Hey, anything worth doing is. And we're gonna teach you.\n:::\n\n::::\n\n### Winning\n\n![20-game winning streak](Oakland_Athletics_winning_streak.png)\n::::\n\n# Era Adjustment\n\n## Milestone Home Run Totals\n\n:::: {.panel-tabset}\n\n### Records\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n![Roger Maris](Roger_Maris.png)\n:::\n\n::: {.column width=\"5%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n* Roger Maris hit 61 home runs in 1961\n* Aaron Judge hit 62 home runs in 2022\n\n    * American League records\n:::\n\n::: {.column width=\"5%\"}\n\n:::\n\n::: {.column width=\"20%\"}\n![Aaron Judge](Aaron_Judge.png)\n:::\n\n::::\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLahman::Batting |>\n  filter(yearID %in% c(\"1961\", \"2022\")) |>\n  filter(AB >= 100) |>\n  group_by(yearID) |>\n  summarize(xbar = mean(HR, na.rm = TRUE),\n            s = sd(HR, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  yearID  xbar     s\n   <int> <dbl> <dbl>\n1   1961  10.8 10.8 \n2   2022  10.6  8.91\n```\n\n\n:::\n:::\n\n\n\n### Z-Scores\n\n$$z_{M} = \\frac{61 - \\bar{x}_{2022}}{s_{2022}} = \\frac{61 - 10.7615}{10.7928} \\approx 4.6548$$\nRoger Maris' home run record was about 4.6548 standard deviations above the mean in 1961.\n\n$$z_{J} = \\frac{62 - \\bar{x}_{2022}}{s_{2022}} = \\frac{62 - 10.5729}{8.9065} \\approx 5.7741$$\n\nAaron Judge's home run record was about 5.7741 standard deviations above the mean in 2022.\n\n### Switch\n\n$$4.6548 = \\frac{x_{M} - \\bar{x}_{2022}}{s_{2022}} = \\frac{x_{M} - 10.5729}{8.9065} \\Rightarrow x_{M} \\approx 52.0388$$\n\n$$5.7741 = \\frac{x_{J} - \\bar{x}_{1961}}{s_{1961}} = \\frac{x_{J} - 10.7615}{10.7928} \\Rightarrow x_{J} \\approx 73.0802$$\n\n### What If\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n![Roger Maris](Roger_Maris_color.png)\n:::\n\n::: {.column width=\"5%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n* Roger Maris would have hit 52 home runs is 2022\n* Aaron Judge would have hit 73 home runs in 1961\n:::\n\n::: {.column width=\"5%\"}\n\n:::\n\n::: {.column width=\"20%\"}\n![Aaron Judge](Aaron_Judge_grayscale.png)\n:::\n\n::::\n\n::::\n\n\n# Precept 5\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* NBA basketball data\n* 2013 to 2023\n* practice data science skills from semester so far\n* start building linear regression models\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n![Warriors@Pacers](nba_2013.png)\n:::\n\n::::\n\n\n\n\n# Quo Vadimus?\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* Continue to complete BLTs and precept assignments\n* Project 1 Due: Oct 2\n* Exam 1: Oct 10\n* Refer to weekly announcement for more info\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n![Oakland Coliseum](Oakland_Coliseum.png)\n\n* Derek is reminiscing about the games back in Oakland.\n:::\n\n::::\n\n\n# Footnotes\n\n::: {.callout-note collapse=\"true\"}\n## (optional) Additional Resources\n\nIf anyone is interested into a deeper study of the data wrangling in *Moneyball*, you can take the online course [Moneyball and Beyond](https://www.coursera.org/specializations/sports-analytics) offered by the University of Michigan as part of the Coursera specialization in Sports Performance Analytics\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.4.1 (2024-06-14 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.3 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4    \n [5] purrr_1.0.2     readr_2.1.5     tidyr_1.3.1     tibble_3.2.1   \n [9] ggplot2_3.5.1   tidyverse_2.0.0 gt_0.11.0       corrplot_0.94  \n\nloaded via a namespace (and not attached):\n [1] sass_0.4.9        utf8_1.2.4        generics_0.1.3    xml2_1.3.6       \n [5] lattice_0.22-6    stringi_1.8.4     hms_1.1.3         digest_0.6.35    \n [9] magrittr_2.0.3    evaluate_0.24.0   grid_4.4.1        timechange_0.3.0 \n[13] fastmap_1.2.0     Matrix_1.7-0      jsonlite_1.8.8    mgcv_1.9-1       \n[17] fansi_1.0.6       scales_1.3.0      cli_3.6.2         rlang_1.1.4      \n[21] crayon_1.5.3      Lahman_12.0-0     splines_4.4.1     bit64_4.0.5      \n[25] munsell_0.5.1     withr_3.0.1       yaml_2.3.8        tools_4.4.1      \n[29] parallel_4.4.1    tzdb_0.4.0        colorspace_2.1-1  curl_5.2.1       \n[33] vctrs_0.6.5       R6_2.5.1          lifecycle_1.0.4   htmlwidgets_1.6.4\n[37] bit_4.0.5         vroom_1.6.5       pkgconfig_2.0.3   pillar_1.9.0     \n[41] gtable_0.3.5      glue_1.7.0        xfun_0.44         tidyselect_1.2.1 \n[45] rstudioapi_0.16.0 knitr_1.48        farver_2.1.2      nlme_3.1-164     \n[49] htmltools_0.5.8.1 labeling_0.4.3    rmarkdown_2.27    compiler_4.4.1   \n```\n\n\n:::\n:::\n\n\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Example Callout Block\n\n`note`, `tip`, `warning`, `caution`, or `important`\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n:::: {.panel-tabset}\n\n\n\n::::",
    "supporting": [
      "09_multiple_linear_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}