{
  "hash": "6d0e0b650cb9ea44c28f2cdae89bd2e6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"9: Modeling Categorical Variables\"\nauthor: \"Derek Sollberger\"\ndate: \"2026-02-24\"\nformat:\n  html:\n    toc: true\n    theme: cerulean\n---\n\n\n# SML 201\n\n## Start\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* **Goal**: Utilize categorical variables in regression models\n\n* **Objective**: Explore one-hot encoding and start classification\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n![multiple slopes!](multiple_slopes.png)\n:::\n\n::::\n\n::: {.callout-note collapse=\"true\"}\n## code packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"janitor\")   #tools for data cleaning\nlibrary(\"tidyverse\") #tools for data wrangling and visualization\n\nprinceton_orange <- \"#E77500\"\nprinceton_black  <- \"#121212\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df <- readr::read_csv(\"loan_data_set.csv\") |>\n  janitor::clean_names()\n```\n:::\n\n:::\n\n## Data\n\n::::: {.panel-tabset}\n\n## Description\n\n:::: {.columns}\n\n::: {.column width=\"60%\"}\n\"Dream Housing Finance company deals in all home loans. They have presence across all urban, semi urban and rural areas. Customer first apply for home loan after that company validates the customer eligibility for loan.\"\t\n\n* Source: [Kaggle](https://www.kaggle.com/datasets/burak3ergun/loan-data-set)\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"30%\"}\n![Dream Home Finance](Dream_Home_Finance.png)\n:::\n\n::::\n\n## Scenario\n\n\"Company wants to automate the loan eligibility process (real time) based on customer detail provided while filling online application form. These details are Gender, Marital Status, Education, Number of Dependents, Income, Loan Amount, Credit History and others. To automate this process, they have given a problem to identify the customers segments, those are eligible for loan amount so that they can specifically target these customers. Here they have provided a partial data set.\"\n\n## Response Variable\n\nWe will try to predict the loan amount (i.e. numerical variable)\n\n* Loan amount (in thousands of dollars)\n\n## Explanatory Variables\n\n* Gender (of primary applicant)\n* Marital status (of primary applicant)\n* Dependents \n* Education\n* Self-employed\n* Applicant income (monthly, in dollars)\n* Co-applicant income (monthly, in dollars)\n* loan amount terms (in months)\n* Credit history\n* Property area\n\n:::::\n\n## Cleaning\n\n* remove rows that have missing values in the response variable (`loan_amount`)\n* convert `dependents` to a numerical variable\n\n    * here, replace \"+\" with nothing\n\n* combine \"income\" columns\n\n    * ensure all dollar amounts are in the same units (thousands of dollars)\n\n* convert `credit_history` to a factor variable (i.e. categorical)\n\n* retain relevant columns\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df <- loan_df |>\n  filter(!is.na(loan_amount)) |>\n  mutate(dependents_num = as.numeric(\n    str_replace(dependents, \"\\\\+\", \"\")\n  )) |>\n  mutate(income = applicant_income/1000 + coapplicant_income/1000) |>\n  mutate(credit_history = factor(credit_history)) |>\n  select(loan_amount, income, dependents_num, gender, married, education, self_employed, credit_history, property_area, loan_status)\n```\n:::\n\n\nAfter cleaning the data, we should report the size of the resultant data frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(loan_df) #number of observations\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 592\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(loan_df) #number of variables\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\nand the structure of the data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(loan_df, give.attr = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [592 × 10] (S3: tbl_df/tbl/data.frame)\n $ loan_amount   : num [1:592] 128 66 120 141 267 95 158 168 349 70 ...\n $ income        : num [1:592] 6.09 3 4.94 6 9.61 ...\n $ dependents_num: num [1:592] 1 0 0 0 2 0 3 2 1 2 ...\n $ gender        : chr [1:592] \"Male\" \"Male\" \"Male\" \"Male\" ...\n $ married       : chr [1:592] \"Yes\" \"Yes\" \"Yes\" \"No\" ...\n $ education     : chr [1:592] \"Graduate\" \"Graduate\" \"Not Graduate\" \"Graduate\" ...\n $ self_employed : chr [1:592] \"No\" \"Yes\" \"No\" \"No\" ...\n $ credit_history: Factor w/ 2 levels \"0\",\"1\": 2 2 2 2 2 2 1 2 2 2 ...\n $ property_area : chr [1:592] \"Rural\" \"Urban\" \"Urban\" \"Urban\" ...\n $ loan_status   : chr [1:592] \"N\" \"Y\" \"Y\" \"Y\" ...\n```\n\n\n:::\n:::\n\n\n\n# Multiple Linear Regression\n\n## Scenario 1:\n\n* response variable: `loan_amount`\n* explanatory variables:\n\n    * `income`\n    * `dependents_num`\n\n## Build the Model\n    \n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(loan_amount ~ income + dependents_num, data = loan_df)\n```\n:::\n\n\n## Interpretation\n\nSometimes we interpret the slopes to see if the found coefficients make sense in context.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num, data = loan_df)\n\nCoefficients:\n   (Intercept)          income  dependents_num  \n        84.518           8.048           6.943  \n```\n\n\n:::\n:::\n\n\n> Holding dependents constant, for each $1000 increase in monthly income, the loan amount increases by about $8000\n\n> Holding income constant, for each additional dependent, the loan amount increases by about $7000\n\n::: {.callout-tip collapse=\"true\"}\n## Intercept\n\nCan you interpret the intercept value too?  Does that make sense to you?\n:::\n\n\n## Determination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod1)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3955349\n```\n\n\n:::\n:::\n\n\n> For this baseline model, the coefficient of determination states that we can explain about 40 percent of the variance in loan amount with these two numerical explanatory variables.\n\n\n# Categorical Input\n\nLet us expand the model to include `credit_history`.\n\n$$\\text{Credit History} = \\begin{cases} 1, & \\text{passed credit check} \\\\\n0, & \\text{did not pass credit check} \\\\ \\end{cases}$$\n\nWe are treating this variable as *categorical*.\n\n## Scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df |>\n  filter(!is.na(credit_history)) |>\n  ggplot(aes(x = income, y = loan_amount, color = credit_history)) +\n  geom_point() +\n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              se = FALSE) +\n  labs(title = \"Dream Home Finance\",\n       subtitle = \"Interaction Plot\",\n       caption = \"SML 201\",\n       x = \"combined monthly income (thousands)\",\n       y = \"loan amount (thousands)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_explain_cats_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2_without_interaction <- lm(loan_amount ~ income + \n                                 dependents_num +\n                                 credit_history,\n                               data = loan_df)\n```\n:::\n\n\n## Model Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod2_without_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num + credit_history, \n    data = loan_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-372.17  -28.38   -5.71   21.62  356.55 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      82.5113     8.2910   9.952  < 2e-16 ***\nincome            7.6934     0.4386  17.539  < 2e-16 ***\ndependents_num    8.8323     2.8231   3.129  0.00185 ** \ncredit_history1   2.2122     7.9957   0.277  0.78214    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 65.84 on 526 degrees of freedom\n  (62 observations deleted due to missingness)\nMultiple R-squared:  0.3908,\tAdjusted R-squared:  0.3873 \nF-statistic: 112.5 on 3 and 526 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Interpretation\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{1}X_{3} \\\\\n~ & \\approx & 81.7427 + 6.4019X_{1} + 9.3093X_{2} + 1.9206X_{3}\n\\end{array}$$\n\nwhere\n\n$$X_{1}: \\text{income}, \\quad X_{2}: \\text{number of dependents}$$\n\nand\n\n$$X_{3} = \\begin{cases} 1, & \\text{passed credit check} \\\\\n0, & \\text{did not pass credit check} \\\\ \\end{cases}$$\n\n> Passing the credit check increases the home loan by about $2000 (??)\n\n::: {.callout-warning}\n## DCP1\n:::\n\n\n# Interaction Term\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{1}X_{3} \\\\\n\\end{array}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2_with_interaction <- lm(loan_amount ~ income +\n                              dependents_num +\n                              income:credit_history,\n                            data = loan_df)\n```\n:::\n\n\n## Refined Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod2_with_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num + income:credit_history, \n    data = loan_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-327.08  -28.02   -4.70   21.74  346.79 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             81.7427     4.6271  17.666  < 2e-16 ***\nincome                   6.4019     0.6430   9.957  < 2e-16 ***\ndependents_num           9.3093     2.8080   3.315 0.000979 ***\nincome:credit_history1   1.9206     0.7048   2.725 0.006646 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 65.38 on 526 degrees of freedom\n  (62 observations deleted due to missingness)\nMultiple R-squared:  0.3992,\tAdjusted R-squared:  0.3957 \nF-statistic: 116.5 on 3 and 526 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{1}X_{3} \\\\\n~ & = & 81.7427 + 6.4019X_{1} + 9.3093X_{2} + 1.9206X_{1}X_{3} \\\\\n\\end{array}$$\n\n* For a family with $X_{2} = 0$ dependents and bad credit history ($X_{3} = 0$)\n\n$$Y = 81.7427 + 6.4019X_{1}$$\n\n> For each $1000 increase in monthly income, the loan amount increases by about $6400.\n\n* For a family with $X_{2} = 0$ dependents and good credit history ($X_{3} = 1$)\n\n$$Y = 81.7427 + 6.4019X_{1} + 1.9206X_{1}$$\n\n> For each $1000 increase in monthly income, the loan amount increases by about $8300.\n\n::: {.callout-warning}\n## DCP2\n:::\n\n\n## Determination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod2_with_interaction)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3957492\n```\n\n\n:::\n:::\n\n\n> For this model with an interaction term and the two original explanatory variables, the coefficient of determination shows that we can explain about 40 percent of the variance in the loan amount.\n\n::: {.callout-note collapse=\"true\"}\n## How Complex Should Models Be?\n\nDid you catch that?\n\n* `mod1` had a coefficient of determination of about 0.3955\n* `mod2_with_interaction` had a coefficient of determination of about 0.3957\n\nWith hardly any gains in explaning variance, an analyst might opt to continue with the *simpler model* (here: `mod1`) moving forward in an analysis since it eases *interpretability*\n\n:::\n\n# Parallel Slopes\n\n## Scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df |>\n  filter(!is.na(credit_history)) |>\n  ggplot(aes(x = income, y = loan_amount, color = education)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              se = FALSE) +\n  labs(title = \"Dream Home Finance\",\n       subtitle = \"Parallel Slopes?\",\n       caption = \"SML 201\",\n       x = \"combined monthly income (thousands)\",\n       y = \"loan amount (thousands)\") +\n  scale_color_manual(values = c(\"gray\", \"darkgreen\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_explain_cats_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Model 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod3_without_interaction <- lm(loan_amount ~ income + \n                                 dependents_num +\n                                 education,\n                               data = loan_df)\n```\n:::\n\n\n## Model Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod3_without_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num + education, \n    data = loan_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-388.68  -28.33   -6.10   20.14  402.21 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            89.1379     4.7793  18.651  < 2e-16 ***\nincome                  7.8672     0.4314  18.238  < 2e-16 ***\ndependents_num          7.4332     2.7706   2.683  0.00751 ** \neducationNot Graduate -17.4739     6.8909  -2.536  0.01148 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 66.82 on 575 degrees of freedom\n  (13 observations deleted due to missingness)\nMultiple R-squared:  0.4043,\tAdjusted R-squared:  0.4012 \nF-statistic: 130.1 on 3 and 575 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Interpretation\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{1}X_{3} \\\\\n~ & \\approx & 89.1379 + 7.8672X_{1} + 7.4332X_{2} - 17.4739X_{3}\n\\end{array}$$\n\nwhere\n\n$$X_{1}: \\text{income}, \\quad X_{2}: \\text{number of dependents}$$\n\nand\n\n$$X_{3} = \\begin{cases} 1, & \\text{did not graduate from college} \\\\\n0, & \\text{graduated college} \\\\ \\end{cases}$$\n\n> Those who did not graduate from college had a home loan value that was lower by about $17500.\n\n## Interaction Term\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{1}X_{3} \\\\\n\\end{array}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod3_with_interaction <- lm(loan_amount ~ income +\n                              dependents_num +\n                              income:education,\n                            data = loan_df)\n```\n:::\n\n\n## Refined Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod3_with_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num + income:education, \n    data = loan_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-395.44  -28.18   -6.58   21.03  401.70 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                   87.3028     4.6628  18.723   <2e-16 ***\nincome                         7.9834     0.4278  18.662   <2e-16 ***\ndependents_num                 7.1590     2.7728   2.582   0.0101 *  \nincome:educationNot Graduate  -2.3047     1.2066  -1.910   0.0566 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 66.98 on 575 degrees of freedom\n  (13 observations deleted due to missingness)\nMultiple R-squared:  0.4014,\tAdjusted R-squared:  0.3983 \nF-statistic: 128.5 on 3 and 575 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{1}X_{3} \\\\\n~ & = & 87.3028 + 7.9834X_{1} + 7.1590X_{2} - 2.3047X_{1}X_{3} \\\\\n\\end{array}$$\n\n* For a family with $X_{2} = 2$ dependents and graduated from college ($X_{3} = 0$)\n\n$$Y = 87.3028 + 7.9834X_{1} + 14.3180$$\n\n> For each $1000 increase in monthly income, the loan amount increases by about $8000.\n\n* For a family with $X_{2} = 2$ dependents and did not graduate from college ($X_{3} = 1$)\n\n$$Y = 81.7427 + 7.9834X_{1} + 14.3180 - 2.3047X_{1}$$\n\n> For each $1000 increase in monthly income, the loan amount increases by about $5600.\n\n\n## Determination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod3_with_interaction)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3983014\n```\n\n\n:::\n:::\n\n\n> For this model with an interaction term and the two original explanatory variables, the coefficient of determination shows that we can explain about 40 percent of the variance in the loan amount.\n\n::: {.callout-note collapse=\"true\"}\n## Reordering Factors\n\nYou may have noticed that `R` tends to output categorical variables in alphabetical order by default (e.g. the bars in a bar chart).  If you want to customize the order presented, you would need to employ a **factor** variable where you can explicitly set the **levels**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df <- loan_df |>\n  mutate(education_fac = \n           factor(education,\n                  levels = c(\"Not Graduate\", \"Graduate\")))\n```\n:::\n\n\nNow, the software will treat \"Not Graduate\" as the baseline and \"Graduate\" as the augmentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod4 <- lm(loan_amount ~ income + dependents_num + \n             education_fac,\n           data = loan_df)\nsummary(mod4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num + education_fac, \n    data = loan_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-388.68  -28.33   -6.10   20.14  402.21 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            71.6640     6.7245  10.657  < 2e-16 ***\nincome                  7.8672     0.4314  18.238  < 2e-16 ***\ndependents_num          7.4332     2.7706   2.683  0.00751 ** \neducation_facGraduate  17.4739     6.8909   2.536  0.01148 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 66.82 on 575 degrees of freedom\n  (13 observations deleted due to missingness)\nMultiple R-squared:  0.4043,\tAdjusted R-squared:  0.4012 \nF-statistic: 130.1 on 3 and 575 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df |>\n  filter(!is.na(education_fac)) |>\n  ggplot(aes(x = income, y = loan_amount, color = education_fac)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              se = FALSE) +\n  labs(title = \"Dream Home Finance\",\n       subtitle = \"Parallel Slopes?\",\n       caption = \"SML 201\",\n       x = \"combined monthly income (thousands)\",\n       y = \"loan amount (thousands)\") +\n  scale_color_manual(values = c(\"gray\", \"#E77500\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_explain_cats_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n# Multiple Categories\n\nWhat if our categorical variable has *more than two* labels?  Here, let us explore the `property_area` categorical variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(loan_df$property_area)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Rural Semiurban     Urban \n      173       228       191 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df |>\n  filter(!is.na(property_area)) |>\n  ggplot(aes(x = income, y = loan_amount, color = property_area)) +\n  geom_point() +\n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              se = FALSE) +\n  labs(title = \"Dream Home Finance\",\n       subtitle = \"Parallel Slopes?\",\n       caption = \"SML 201\",\n       x = \"combined monthly income (thousands)\",\n       y = \"loan amount (thousands)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_explain_cats_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n## Label Encoding\n\n::: {.callout-warning}\n### Labeller in practice\n\n*Caution*: Label encoding is usually not recommended in general.  I include this section here for posterity.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1337)\nloan_df |>\n  mutate(property_type = case_when(\n    property_area == \"Rural\" ~ 0,\n    property_area == \"Semiurban\" ~ 1,\n    property_area == \"Urban\" ~ 2,\n    TRUE ~ -1\n  )) |>\n  select(property_area, property_type) |>\n  sample_n(size = 10, replace = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   property_area property_type\n   <chr>                 <dbl>\n 1 Semiurban                 1\n 2 Semiurban                 1\n 3 Semiurban                 1\n 4 Rural                     0\n 5 Rural                     0\n 6 Semiurban                 1\n 7 Semiurban                 1\n 8 Semiurban                 1\n 9 Urban                     2\n10 Semiurban                 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Numerical?\n\nCould we then use `property_type` in a regression model?\n:::\n\n::: {.callout-warning}\n## Ordinal\n\n*Caution*: Label encoding here implied ranking\n\n* *order*: \"Rural\", then \"Semiurban\", then \"Urban\"\n* *proportions*: Is \"Urban\" (with a coefficient of 2) twice as valuable as \"Semiurban\"?\n:::\n\n\n## One-Hot Encoding\n\nSimilar to previous calculations, our `R` software employs **dummy variables** or **one-hot encoding** to represent categories as ones and zeroes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1337)\nloan_df |>\n  mutate(rural_bool = ifelse(property_area == \"Rural\", 1, 0),\n         semiu_bool = ifelse(property_area == \"Semiurban\", 1, 0),\n         urban_bool = ifelse(property_area == \"Urban\", 1, 0)) |>\n  select(property_area, rural_bool, semiu_bool, urban_bool) |>\n  sample_n(size = 10, replace = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   property_area rural_bool semiu_bool urban_bool\n   <chr>              <dbl>      <dbl>      <dbl>\n 1 Semiurban              0          1          0\n 2 Semiurban              0          1          0\n 3 Semiurban              0          1          0\n 4 Rural                  1          0          0\n 5 Rural                  1          0          0\n 6 Semiurban              0          1          0\n 7 Semiurban              0          1          0\n 8 Semiurban              0          1          0\n 9 Urban                  0          0          1\n10 Semiurban              0          1          0\n```\n\n\n:::\n:::\n\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{3} + \\beta_{4}X_{4} \\\\\n\\end{array}$$\n\nwhere\n\n$$X_{1}: \\text{income}, \\quad X_{2}: \\text{number of dependents}$$\n\nand\n\n$$\\begin{array}{rcl}\n  X_{3} & = & \\begin{cases} 1, \\text{semiurban area} \\\\ 0, \\text{otherwise} \\\\ \\end{cases} \\\\\n  X_{4} & = & \\begin{cases} 1, \\text{urban area} \\\\ 0, \\text{otherwise} \\\\ \\end{cases} \\\\\n\\end{array}$$\n\n::: {.callout-warning}\n## DCP3\n:::\n\n\n## Model 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod5 <- lm(loan_amount ~ income + \n             dependents_num +\n             property_area,\n           data = loan_df)\n```\n:::\n\n\n## Model Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = loan_amount ~ income + dependents_num + property_area, \n    data = loan_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-402.72  -28.36   -7.05   19.80  409.16 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             89.1639     6.1868  14.412   <2e-16 ***\nincome                   8.0575     0.4275  18.849   <2e-16 ***\ndependents_num           6.9669     2.7760   2.510   0.0124 *  \nproperty_areaSemiurban  -3.3175     6.8229  -0.486   0.6270    \nproperty_areaUrban     -10.8084     7.1188  -1.518   0.1295    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 67.1 on 574 degrees of freedom\n  (13 observations deleted due to missingness)\nMultiple R-squared:  0.4002,\tAdjusted R-squared:  0.396 \nF-statistic: 95.75 on 4 and 574 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Interpretation\n\n$$\\begin{array}{rcl}\nY & = & \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{3} + \\beta_{4}X_{4} \\\\\n~ & = & 89.1639 + 8.0575X_{1} + 6.9669X_{2} - 3.3175X_{3} - 10.8084X_{4} \\\\\n\\end{array}$$\n\nFor a family with one dependent ($X_{2} = 1$) and a combined monthly income of \\$5000 ($X_{1} = 5$),\n\n* if they are seeking a home in a *rural* area ($X_{3} = 0, X_{4} = 0$), the loan amount is predicted to be about 136 thousand\n* if they are seeking a home in a *semi-urban* area ($X_{3} = 1, X_{4} = 0$), the loan amount is predicted to be about 133 thousand (i.e. 3 thousand less than the baseline rural  scenario)\n* if they are seeking a home in an *urban* area ($X_{3} = 0, X_{4} = 1$), the loan amount is predicted to be about 126 thousand (i.e. 10 thousand less than the baseline rural scenario)\n\n\n\n\n\n# Quo Vadimus?\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* This week: \n\n  * Precept 5\n  * Read Chapter 6\n\n* Exam 1: March 5\n* Refer to weekly announcement for more info\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n![Cloak of Wisdom](cloak_of_wisdom.png)\n\n* image source: [Up and Out Comics](https://www.juliakaye.com/chbeaqv6vde7qjpcppullvaooox6gj)\n:::\n\n::::\n\n\n# Footnotes\n\n::: {.callout-note collapse=\"true\"}\n## (optional) Additional Resources\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df |>\n  filter(!is.na(credit_history)) |>\n  filter(!is.na(dependents_num)) |>\n  ggplot(aes(x = dependents_num, y = loan_amount, color = credit_history, group = credit_history)) +\n  geom_point() +\n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              se = FALSE) +\n  labs(title = \"Dream Home Finance\",\n       subtitle = \"Parallel Slopes?\",\n       caption = \"SML 201\",\n       x = \"number of dependents\",\n       y = \"loan amount\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_explain_cats_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_df |>\n  filter(!is.na(credit_history)) |>\n  filter(!is.na(gender)) |>\n  ggplot(aes(x = income, y = loan_amount, color = gender, group = gender)) +\n  geom_point() +\n  geom_smooth(formula = \"y ~ x\",\n              method = \"lm\",\n              se = FALSE) +\n  labs(title = \"Dream Home Finance\",\n       subtitle = \"Interaction Plot\",\n       caption = \"SML 201\",\n       x = \"income\",\n       y = \"loan amount\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_explain_cats_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.4 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4    \n [5] purrr_1.1.0     readr_2.1.5     tidyr_1.3.1     tibble_3.3.0   \n [9] ggplot2_4.0.0   tidyverse_2.0.0 janitor_2.2.1  \n\nloaded via a namespace (and not attached):\n [1] utf8_1.2.6         generics_0.1.4     lattice_0.22-7     stringi_1.8.7     \n [5] hms_1.1.3          digest_0.6.37      magrittr_2.0.3     evaluate_1.0.4    \n [9] grid_4.5.2         timechange_0.3.0   RColorBrewer_1.1-3 fastmap_1.2.0     \n[13] Matrix_1.7-4       jsonlite_2.0.0     mgcv_1.9-3         scales_1.4.0      \n[17] cli_3.6.5          rlang_1.1.6        crayon_1.5.3       splines_4.5.2     \n[21] bit64_4.6.0-1      withr_3.0.2        yaml_2.3.10        tools_4.5.2       \n[25] parallel_4.5.2     tzdb_0.5.0         vctrs_0.6.5        R6_2.6.1          \n[29] lifecycle_1.0.4    snakecase_0.11.1   htmlwidgets_1.6.4  bit_4.6.0         \n[33] vroom_1.6.5        pkgconfig_2.0.3    pillar_1.11.0      gtable_0.3.6      \n[37] glue_1.8.0         xfun_0.52          tidyselect_1.2.1   rstudioapi_0.17.1 \n[41] knitr_1.50         farver_2.1.2       nlme_3.1-168       htmltools_0.5.8.1 \n[45] labeling_0.4.3     rmarkdown_2.29     compiler_4.5.2     S7_0.2.0          \n```\n\n\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n::::: {.panel-tabset}\n\n\n\n:::::",
    "supporting": [
      "09_explain_cats_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}